/**
 * Created by 李景磊 on 2017-04-10.
 */
var industryCodeJson = [
    {"industry_code":"A",   "industry_name":"农、林、牧、渔业"},
    {"industry_code":"01",  "industry_name":"农业"},
    {"industry_code":"011", "industry_name":"谷物种植"},
    {"industry_code":"0111","industry_name":"稻谷种植"},
    {"industry_code":"0112","industry_name":"小麦种植"},
    {"industry_code":"0113","industry_name":"玉米种植"},
    {"industry_code":"0119","industry_name":"其他谷物种植"},
    {"industry_code":"012", "industry_name":"豆类、油料和薯类种植"},
    {"industry_code":"0121","industry_name":"豆类种植"},
    {"industry_code":"0122","industry_name":"油料种植"},
    {"industry_code":"0123","industry_name":"薯类种植"},
    {"industry_code":"013", "industry_name":"棉、麻、糖、烟草种植"},
    {"industry_code":"0131","industry_name":"棉花种植"},
    {"industry_code":"0132","industry_name":"麻类种植"},
    {"industry_code":"0133","industry_name":"糖料种植"},
    {"industry_code":"0134","industry_name":"烟草种植"},
    {"industry_code":"014", "industry_name":"蔬菜、食用菌及园艺作物种植"},
    {"industry_code":"0141","industry_name":"蔬菜种植"},
    {"industry_code":"0142","industry_name":"食用菌种植"},
    {"industry_code":"0143","industry_name":"花卉种植"},
    {"industry_code":"0149","industry_name":"其他园艺作物种植"},
    {"industry_code":"015", "industry_name":"水果种植"},
    {"industry_code":"0151","industry_name":"仁果类和核果类水果种植"},
    {"industry_code":"0152","industry_name":"葡萄种植"},
    {"industry_code":"0153","industry_name":"柑橘类种植"},
    {"industry_code":"0154","industry_name":"香蕉等亚热带水果种植"},
    {"industry_code":"0159","industry_name":"其他水果种植"},
    {"industry_code":"016", "industry_name":"坚果、含油果、香料和饮料作物种植"},
    {"industry_code":"0161","industry_name":"坚果种植"},
    {"industry_code":"0162","industry_name":"含油果种植"},
    {"industry_code":"0163","industry_name":"香料作物种植"},
    {"industry_code":"0169","industry_name":"茶及其他饮料作物种植"},
    {"industry_code":"017", "industry_name":"中药材种植"},
    {"industry_code":"0170","industry_name":"中药材种植"},
    {"industry_code":"019", "industry_name":"其他农业"},
    {"industry_code":"0190","industry_name":"其他农业"},
    {"industry_code":"02",  "industry_name":"林业"},
    {"industry_code":"021", "industry_name":"林木育种和育苗"},
    {"industry_code":"0211","industry_name":"林木育种"},
    {"industry_code":"0212","industry_name":"林木育苗"},
    {"industry_code":"022", "industry_name":"造林和更新"},
    {"industry_code":"0220","industry_name":"造林和更新"},
    {"industry_code":"023", "industry_name":"森林经营和管护"},
    {"industry_code":"0230","industry_name":"森林经营和管护"},
    {"industry_code":"024", "industry_name":"木材和竹材采运"},
    {"industry_code":"0241","industry_name":"木材采运"},
    {"industry_code":"0242","industry_name":"竹材采运"},
    {"industry_code":"025", "industry_name":"林产品采集"},
    {"industry_code":"0251","industry_name":"木竹材林产品采集"},
    {"industry_code":"0252","industry_name":"非木竹材林产品采集"},
    {"industry_code":"03",  "industry_name":"畜牧业"},
    {"industry_code":"031", "industry_name":"牲畜饲养"},
    {"industry_code":"0311","industry_name":"牛的饲养"},
    {"industry_code":"0312","industry_name":"马的饲养"},
    {"industry_code":"0313","industry_name":"猪的饲养"},
    {"industry_code":"0314","industry_name":"羊的饲养"},
    {"industry_code":"0315","industry_name":"骆驼饲养"},
    {"industry_code":"0319","industry_name":"其他牲畜饲养"},
    {"industry_code":"032", "industry_name":"家禽饲养"},
    {"industry_code":"0321","industry_name":"鸡的饲养"},
    {"industry_code":"0322","industry_name":"鸭的饲养"},
    {"industry_code":"0323","industry_name":"鹅的饲养"},
    {"industry_code":"0329","industry_name":"其他家禽饲养"},
    {"industry_code":"033", "industry_name":"狩猎和捕捉动物"},
    {"industry_code":"0330","industry_name":"狩猎和捕捉动物"},
    {"industry_code":"039", "industry_name":"其他畜牧业"},
    {"industry_code":"0390","industry_name":"其他畜牧业"},
    {"industry_code":"04",  "industry_name":"渔业"},
    {"industry_code":"041", "industry_name":"水产养殖"},
    {"industry_code":"0411","industry_name":"海水养殖"},
    {"industry_code":"0412","industry_name":"内陆养殖"},
    {"industry_code":"042", "industry_name":"水产捕捞"},
    {"industry_code":"0421","industry_name":"海水捕捞"},
    {"industry_code":"0422","industry_name":"内陆捕捞"},
    {"industry_code":"05",  "industry_name":"农、林、牧、渔服务业"},
    {"industry_code":"051", "industry_name":"农业服务业"},
    {"industry_code":"0511","industry_name":"农业机械服务"},
    {"industry_code":"0512","industry_name":"灌溉服务"},
    {"industry_code":"0513","industry_name":"农产品初加工服务"},
    {"industry_code":"0519","industry_name":"其他农业服务"},
    {"industry_code":"052", "industry_name":"林业服务业"},
    {"industry_code":"0521","industry_name":"林业有害生物防治服务"},
    {"industry_code":"0522","industry_name":"森林防火服务"},
    {"industry_code":"0523","industry_name":"林产品初级加工服务"},
    {"industry_code":"0529","industry_name":"其他林业服务"},
    {"industry_code":"053", "industry_name":"畜牧服务业"},
    {"industry_code":"0530","industry_name":"畜牧服务业"},
    {"industry_code":"054", "industry_name":"渔业服务业"},
    {"industry_code":"0540","industry_name":"渔业服务业"},
    {"industry_code":"B",   "industry_name":"采矿业"},
    {"industry_code":"06",  "industry_name":"煤炭开采和洗选业"},
    {"industry_code":"061", "industry_name":"烟煤和无烟煤开采洗选"},
    {"industry_code":"0610","industry_name":"烟煤和无烟煤开采洗选"},
    {"industry_code":"062", "industry_name":"褐煤开采洗选"},
    {"industry_code":"0620","industry_name":"褐煤开采洗选"},
    {"industry_code":"069", "industry_name":"其他煤炭采选"},
    {"industry_code":"0690","industry_name":"其他煤炭采选"},
    {"industry_code":"07",  "industry_name":"石油和天然气开采业"},
    {"industry_code":"071", "industry_name":"石油开采"},
    {"industry_code":"0710","industry_name":"石油开采"},
    {"industry_code":"072", "industry_name":"天然气开采"},
    {"industry_code":"0720","industry_name":"天然气开采"},
    {"industry_code":"08",  "industry_name":"黑色金属矿采选业"},
    {"industry_code":"081", "industry_name":"铁矿采选"},
    {"industry_code":"0810","industry_name":"铁矿采选"},
    {"industry_code":"082", "industry_name":"锰矿、铬矿采选"},
    {"industry_code":"0820","industry_name":"锰矿、铬矿采选"},
    {"industry_code":"089", "industry_name":"其他黑色金属矿采选"},
    {"industry_code":"0890","industry_name":"其他黑色金属矿采选"},
    {"industry_code":"09",  "industry_name":"有色金属矿采选业"},
    {"industry_code":"091", "industry_name":"常用有色金属矿采选"},
    {"industry_code":"0911","industry_name":"铜矿采选"},
    {"industry_code":"0912","industry_name":"铅锌矿采选"},
    {"industry_code":"0913","industry_name":"镍钴矿采选"},
    {"industry_code":"0914","industry_name":"锡矿采选"},
    {"industry_code":"0915","industry_name":"锑矿采选"},
    {"industry_code":"0916","industry_name":"铝矿采选"},
    {"industry_code":"0917","industry_name":"镁矿采选"},
    {"industry_code":"0919","industry_name":"其他常用有色金属矿采选"},
    {"industry_code":"092", "industry_name":"贵金属矿采选"},
    {"industry_code":"0921","industry_name":"金矿采选"},
    {"industry_code":"0922","industry_name":"银矿采选"},
    {"industry_code":"0929","industry_name":"其他贵金属矿采选"},
    {"industry_code":"093", "industry_name":"稀有稀土金属矿采选"},
    {"industry_code":"0931","industry_name":"钨钼矿采选"},
    {"industry_code":"0932","industry_name":"稀土金属矿采选"},
    {"industry_code":"0933","industry_name":"放射性金属矿采选"},
    {"industry_code":"0939","industry_name":"其他稀有金属矿采选"},
    {"industry_code":"10",  "industry_name":"非金属矿采选业"},
    {"industry_code":"101", "industry_name":"土砂石开采"},
    {"industry_code":"1011","industry_name":"石灰石、石膏开采"},
    {"industry_code":"1012","industry_name":"建筑装饰用石开采"},
    {"industry_code":"1013","industry_name":"耐火土石开采"},
    {"industry_code":"1019","industry_name":"粘土及其他土砂石开采"},
    {"industry_code":"102", "industry_name":"化学矿开采"},
    {"industry_code":"1020","industry_name":"化学矿开采"},
    {"industry_code":"103", "industry_name":"采盐"},
    {"industry_code":"1030","industry_name":"采盐"},
    {"industry_code":"109", "industry_name":"石棉及其他非金属矿采选"},
    {"industry_code":"1091","industry_name":"石棉、云母矿采选"},
    {"industry_code":"1092","industry_name":"石墨、滑石采选"},
    {"industry_code":"1093","industry_name":"宝石、玉石采选"},
    {"industry_code":"1099","industry_name":"其他未列明非金属矿采选"},
    {"industry_code":"11",  "industry_name":"开采辅助活动"},
    {"industry_code":"111", "industry_name":"煤炭开采和洗选辅助活动"},
    {"industry_code":"1110","industry_name":"煤炭开采和洗选辅助活动"},
    {"industry_code":"112", "industry_name":"石油和天然气开采辅助活动"},
    {"industry_code":"1120","industry_name":"石油和天然气开采辅助活动"},
    {"industry_code":"119", "industry_name":"其他开采辅助活动"},
    {"industry_code":"1190","industry_name":"其他开采辅助活动"},
    {"industry_code":"12",  "industry_name":"其他采矿业"},
    {"industry_code":"120", "industry_name":"其他采矿业"},
    {"industry_code":"1200","industry_name":"其他采矿业"},
    {"industry_code":"C",   "industry_name":"制造业"},
    {"industry_code":"13",  "industry_name":"农副食品加工业"},
    {"industry_code":"131", "industry_name":"谷物磨制"},
    {"industry_code":"1310","industry_name":"谷物磨制"},
    {"industry_code":"132", "industry_name":"饲料加工"},
    {"industry_code":"1320","industry_name":"饲料加工"},
    {"industry_code":"133", "industry_name":"植物油加工"},
    {"industry_code":"1331","industry_name":"食用植物油加工"},
    {"industry_code":"1332","industry_name":"非食用植物油加工"},
    {"industry_code":"134", "industry_name":"制糖业"},
    {"industry_code":"1340","industry_name":"制糖业"},
    {"industry_code":"135", "industry_name":"屠宰及肉类加工"},
    {"industry_code":"1351","industry_name":"牲畜屠宰"},
    {"industry_code":"1352","industry_name":"禽类屠宰"},
    {"industry_code":"1353","industry_name":"肉制品及副产品加工"},
    {"industry_code":"136", "industry_name":"水产品加工"},
    {"industry_code":"1361","industry_name":"水产品冷冻加工"},
    {"industry_code":"1362","industry_name":"鱼糜制品及水产品干腌制加工"},
    {"industry_code":"1363","industry_name":"水产饲料制造"},
    {"industry_code":"1364","industry_name":"鱼油提取及制品制造"},
    {"industry_code":"1369","industry_name":"其他水产品加工"},
    {"industry_code":"137", "industry_name":"蔬菜、水果和坚果加工"},
    {"industry_code":"1371","industry_name":"蔬菜加工"},
    {"industry_code":"1372","industry_name":"水果和坚果加工"},
    {"industry_code":"139", "industry_name":"其他农副食品加工"},
    {"industry_code":"1391","industry_name":"淀粉及淀粉制品制造"},
    {"industry_code":"1392","industry_name":"豆制品制造"},
    {"industry_code":"1393","industry_name":"蛋品加工"},
    {"industry_code":"1399","industry_name":"其他未列明农副食品加工"},
    {"industry_code":"14",  "industry_name":"食品制造业"},
    {"industry_code":"141", "industry_name":"焙烤食品制造"},
    {"industry_code":"1411","industry_name":"糕点、面包制造"},
    {"industry_code":"1419","industry_name":"饼干及其他焙烤食品制造"},
    {"industry_code":"142", "industry_name":"糖果、巧克力及蜜饯制造"},
    {"industry_code":"1421","industry_name":"糖果、巧克力制造"},
    {"industry_code":"1422","industry_name":"蜜饯制作"},
    {"industry_code":"143", "industry_name":"方便食品制造"},
    {"industry_code":"1431","industry_name":"米、面制品制造"},
    {"industry_code":"1432","industry_name":"速冻食品制造"},
    {"industry_code":"1439","industry_name":"方便面及其他方便食品制造"},
    {"industry_code":"144", "industry_name":"乳制品制造"},
    {"industry_code":"1440","industry_name":"乳制品制造"},
    {"industry_code":"145", "industry_name":"罐头食品制造"},
    {"industry_code":"1451","industry_name":"肉、禽类罐头制造"},
    {"industry_code":"1452","industry_name":"水产品罐头制造"},
    {"industry_code":"1453","industry_name":"蔬菜、水果罐头制造"},
    {"industry_code":"1459","industry_name":"其他罐头食品制造"},
    {"industry_code":"146", "industry_name":"调味品、发酵制品制造"},
    {"industry_code":"1461","industry_name":"味精制造"},
    {"industry_code":"1462","industry_name":"酱油、食醋及类似制品制造"},
    {"industry_code":"1469","industry_name":"其他调味品、发酵制品制造"},
    {"industry_code":"149", "industry_name":"其他食品制造"},
    {"industry_code":"1491","industry_name":"营养食品制造"},
    {"industry_code":"1492","industry_name":"保健食品制造"},
    {"industry_code":"1493","industry_name":"冷冻饮品及食用冰制造"},
    {"industry_code":"1494","industry_name":"盐加工"},
    {"industry_code":"1495","industry_name":"食品及饲料添加剂制造"},
    {"industry_code":"1499","industry_name":"其他未列明食品制造"},
    {"industry_code":"15",  "industry_name":"酒、饮料和精制茶制造业"},
    {"industry_code":"151", "industry_name":"酒的制造"},
    {"industry_code":"1511","industry_name":"酒精制造"},
    {"industry_code":"1512","industry_name":"白酒制造"},
    {"industry_code":"1513","industry_name":"啤酒制造"},
    {"industry_code":"1514","industry_name":"黄酒制造"},
    {"industry_code":"1515","industry_name":"葡萄酒制造"},
    {"industry_code":"1519","industry_name":"其他酒制造"},
    {"industry_code":"152", "industry_name":"饮料制造"},
    {"industry_code":"1521","industry_name":"碳酸饮料制造"},
    {"industry_code":"1522","industry_name":"瓶（罐）装饮用水制造"},
    {"industry_code":"1523","industry_name":"果菜汁及果菜汁饮料制造"},
    {"industry_code":"1524","industry_name":"含乳饮料和植物蛋白饮料制造"},
    {"industry_code":"1525","industry_name":"固体饮料制造"},
    {"industry_code":"1529","industry_name":"茶饮料及其他饮料制造"},
    {"industry_code":"153", "industry_name":"精制茶加工"},
    {"industry_code":"1530","industry_name":"精制茶加工"},
    {"industry_code":"16",  "industry_name":"烟草制品业"},
    {"industry_code":"161", "industry_name":"烟叶复烤"},
    {"industry_code":"1610","industry_name":"烟叶复烤"},
    {"industry_code":"162", "industry_name":"卷烟制造"},
    {"industry_code":"1620","industry_name":"卷烟制造"},
    {"industry_code":"169", "industry_name":"其他烟草制品制造"},
    {"industry_code":"1690","industry_name":"其他烟草制品制造"},
    {"industry_code":"17",  "industry_name":"纺织业"},
    {"industry_code":"171", "industry_name":"棉纺织及印染精加工"},
    {"industry_code":"1711","industry_name":"棉纺纱加工"},
    {"industry_code":"1712","industry_name":"棉织造加工"},
    {"industry_code":"1713","industry_name":"棉印染精加工"},
    {"industry_code":"172", "industry_name":"毛纺织及染整精加工"},
    {"industry_code":"1721","industry_name":"毛条和毛纱线加工"},
    {"industry_code":"1722","industry_name":"毛织造加工"},
    {"industry_code":"1723","industry_name":"毛染整精加工"},
    {"industry_code":"173", "industry_name":"麻纺织及染整精加工"},
    {"industry_code":"1731","industry_name":"麻纤维纺前加工和纺纱"},
    {"industry_code":"1732","industry_name":"麻织造加工"},
    {"industry_code":"1733","industry_name":"麻染整精加工"},
    {"industry_code":"174", "industry_name":"丝绢纺织及印染精加工"},
    {"industry_code":"1741","industry_name":"缫丝加工"},
    {"industry_code":"1742","industry_name":"绢纺和丝织加工"},
    {"industry_code":"1743","industry_name":"丝印染精加工"},
    {"industry_code":"175", "industry_name":"化纤织造及印染精加工"},
    {"industry_code":"1751","industry_name":"化纤织造加工"},
    {"industry_code":"1752","industry_name":"化纤织物染整精加工"},
    {"industry_code":"176", "industry_name":"针织或钩针编织物及其制品制造"},
    {"industry_code":"1761","industry_name":"针织或钩针编织物织造"},
    {"industry_code":"1762","industry_name":"针织或钩针编织物印染精加工"},
    {"industry_code":"1763","industry_name":"针织或钩针编织品制造"},
    {"industry_code":"177", "industry_name":"家用纺织制成品制造"},
    {"industry_code":"1771","industry_name":"床上用品制造"},
    {"industry_code":"1772","industry_name":"毛巾类制品制造"},
    {"industry_code":"1773","industry_name":"窗帘、布艺类产品制造"},
    {"industry_code":"1779","industry_name":"其他家用纺织制成品制造"},
    {"industry_code":"178", "industry_name":"非家用纺织制成品制造"},
    {"industry_code":"1781","industry_name":"非织造布制造"},
    {"industry_code":"1782","industry_name":"绳、索、缆制造"},
    {"industry_code":"1783","industry_name":"纺织带和帘子布制造"},
    {"industry_code":"1784","industry_name":"篷、帆布制造"},
    {"industry_code":"1789","industry_name":"其他非家用纺织制成品制造"},
    {"industry_code":"18",  "industry_name":"纺织服装、服饰业"},
    {"industry_code":"181", "industry_name":"机织服装制造"},
    {"industry_code":"1810","industry_name":"机织服装制造"},
    {"industry_code":"182", "industry_name":"针织或钩针编织服装制造"},
    {"industry_code":"1820","industry_name":"针织或钩针编织服装制造"},
    {"industry_code":"183", "industry_name":"服饰制造"},
    {"industry_code":"1830","industry_name":"服饰制造"},
    {"industry_code":"19",  "industry_name":"皮革、毛皮、羽毛及其制品和制鞋业"},
    {"industry_code":"191", "industry_name":"皮革鞣制加工"},
    {"industry_code":"1910","industry_name":"皮革鞣制加工"},
    {"industry_code":"192", "industry_name":"皮革制品制造"},
    {"industry_code":"1921","industry_name":"皮革服装制造"},
    {"industry_code":"1922","industry_name":"皮箱、包（袋）制造"},
    {"industry_code":"1923","industry_name":"皮手套及皮装饰制品制造"},
    {"industry_code":"1929","industry_name":"其他皮革制品制造"},
    {"industry_code":"193", "industry_name":"毛皮鞣制及制品加工"},
    {"industry_code":"1931","industry_name":"毛皮鞣制加工"},
    {"industry_code":"1932","industry_name":"毛皮服装加工"},
    {"industry_code":"1939","industry_name":"其他毛皮制品加工"},
    {"industry_code":"194", "industry_name":"羽毛(绒)加工及制品制造"},
    {"industry_code":"1941","industry_name":"羽毛（绒）加工"},
    {"industry_code":"1942","industry_name":"羽毛（绒）制品加工"},
    {"industry_code":"195", "industry_name":"制鞋业"},
    {"industry_code":"1951","industry_name":"纺织面料鞋制造"},
    {"industry_code":"1952","industry_name":"皮鞋制造"},
    {"industry_code":"1953","industry_name":"塑料鞋制造"},
    {"industry_code":"1954","industry_name":"橡胶鞋制造"},
    {"industry_code":"1959","industry_name":"其他制鞋业"},
    {"industry_code":"20",  "industry_name":"木材加工和木、竹、藤、棕、草制品业"},
    {"industry_code":"201", "industry_name":"木材加工"},
    {"industry_code":"2011","industry_name":"锯材加工"},
    {"industry_code":"2012","industry_name":"木片加工"},
    {"industry_code":"2013","industry_name":"单板加工"},
    {"industry_code":"2019","industry_name":"其他木材加工"},
    {"industry_code":"202", "industry_name":"人造板制造"},
    {"industry_code":"2021","industry_name":"胶合板制造"},
    {"industry_code":"2022","industry_name":"纤维板制造"},
    {"industry_code":"2023","industry_name":"刨花板制造"},
    {"industry_code":"2029","industry_name":"其他人造板制造"},
    {"industry_code":"203", "industry_name":"木制品制造"},
    {"industry_code":"2031","industry_name":"建筑用木料及木材组件加工"},
    {"industry_code":"2032","industry_name":"木门窗、楼梯制造"},
    {"industry_code":"2033","industry_name":"地板制造"},
    {"industry_code":"2034","industry_name":"木制容器制造"},
    {"industry_code":"2039","industry_name":"软木制品及其他木制品制造"},
    {"industry_code":"204", "industry_name":"竹、藤、棕、草等制品制造"},
    {"industry_code":"2041","industry_name":"竹制品制造"},
    {"industry_code":"2042","industry_name":"藤制品制造"},
    {"industry_code":"2043","industry_name":"棕制品制造"},
    {"industry_code":"2049","industry_name":"草及其他制品制造"},
    {"industry_code":"21",  "industry_name":"家具制造业"},
    {"industry_code":"211", "industry_name":"木质家具制造"},
    {"industry_code":"2110","industry_name":"木质家具制造"},
    {"industry_code":"212", "industry_name":"竹、藤家具制造"},
    {"industry_code":"2120","industry_name":"竹、藤家具制造"},
    {"industry_code":"213", "industry_name":"金属家具制造"},
    {"industry_code":"2130","industry_name":"金属家具制造"},
    {"industry_code":"214", "industry_name":"塑料家具制造"},
    {"industry_code":"2140","industry_name":"塑料家具制造"},
    {"industry_code":"219", "industry_name":"其他家具制造"},
    {"industry_code":"2190","industry_name":"其他家具制造"},
    {"industry_code":"22",  "industry_name":"造纸和纸制品业"},
    {"industry_code":"221", "industry_name":"纸浆制造"},
    {"industry_code":"2211","industry_name":"木竹浆制造"},
    {"industry_code":"2212","industry_name":"非木竹浆制造"},
    {"industry_code":"222", "industry_name":"造纸"},
    {"industry_code":"2221","industry_name":"机制纸及纸板制造"},
    {"industry_code":"2222","industry_name":"手工纸制造"},
    {"industry_code":"2223","industry_name":"加工纸制造"},
    {"industry_code":"223", "industry_name":"纸制品制造"},
    {"industry_code":"2231","industry_name":"纸和纸板容器制造"},
    {"industry_code":"2239","industry_name":"其他纸制品制造"},
    {"industry_code":"23",  "industry_name":"印刷和记录媒介复制业"},
    {"industry_code":"231", "industry_name":"印刷"},
    {"industry_code":"2311","industry_name":"书、报刊印刷"},
    {"industry_code":"2312","industry_name":"本册印制"},
    {"industry_code":"2319","industry_name":"包装装潢及其他印刷"},
    {"industry_code":"232", "industry_name":"装订及印刷相关服务"},
    {"industry_code":"2320","industry_name":"装订及印刷相关服务"},
    {"industry_code":"233", "industry_name":"记录媒介复制"},
    {"industry_code":"2330","industry_name":"记录媒介复制"},
    {"industry_code":"24",  "industry_name":"文教、工美、体育和娱乐用品制造业"},
    {"industry_code":"241", "industry_name":"文教办公用品制造"},
    {"industry_code":"2411","industry_name":"文具制造"},
    {"industry_code":"2412","industry_name":"笔的制造"},
    {"industry_code":"2413","industry_name":"教学用模型及教具制造"},
    {"industry_code":"2414","industry_name":"墨水、墨汁制造"},
    {"industry_code":"2419","industry_name":"其他文教办公用品制造"},
    {"industry_code":"242", "industry_name":"乐器制造"},
    {"industry_code":"2421","industry_name":"中乐器制造"},
    {"industry_code":"2422","industry_name":"西乐器制造"},
    {"industry_code":"2423","industry_name":"电子乐器制造"},
    {"industry_code":"2429","industry_name":"其他乐器及零件制造"},
    {"industry_code":"243", "industry_name":"工艺美术品制造"},
    {"industry_code":"2431","industry_name":"雕塑工艺品制造"},
    {"industry_code":"2432","industry_name":"金属工艺品制造"},
    {"industry_code":"2433","industry_name":"漆器工艺品制造"},
    {"industry_code":"2434","industry_name":"花画工艺品制造"},
    {"industry_code":"2435","industry_name":"天然植物纤维编织工艺品制造"},
    {"industry_code":"2436","industry_name":"抽纱刺绣工艺品制造"},
    {"industry_code":"2437","industry_name":"地毯、挂毯制造"},
    {"industry_code":"2438","industry_name":"珠宝首饰及有关物品制造"},
    {"industry_code":"2439","industry_name":"其他工艺美术品制造"},
    {"industry_code":"244", "industry_name":"体育用品制造"},
    {"industry_code":"2441","industry_name":"球类制造"},
    {"industry_code":"2442","industry_name":"体育器材及配件制造"},
    {"industry_code":"2443","industry_name":"训练健身器材制造"},
    {"industry_code":"2444","industry_name":"运动防护用具制造"},
    {"industry_code":"2449","industry_name":"其他体育用品制造"},
    {"industry_code":"245", "industry_name":"玩具制造"},
    {"industry_code":"2450","industry_name":"玩具制造"},
    {"industry_code":"246", "industry_name":"游艺器材及娱乐用品制造"},
    {"industry_code":"2461","industry_name":"露天游乐场所游乐设备制造"},
    {"industry_code":"2462","industry_name":"游艺用品及室内游艺器材制造"},
    {"industry_code":"2469","industry_name":"其他娱乐用品制造"},
    {"industry_code":"25",  "industry_name":"石油加工、炼焦和核燃料加工业"},
    {"industry_code":"251", "industry_name":"精炼石油产品制造"},
    {"industry_code":"2511","industry_name":"原油加工及石油制品制造"},
    {"industry_code":"2512","industry_name":"人造原油制造"},
    {"industry_code":"252", "industry_name":"炼焦"},
    {"industry_code":"2520","industry_name":"炼焦"},
    {"industry_code":"253", "industry_name":"核燃料加工"},
    {"industry_code":"2530","industry_name":"核燃料加工"},
    {"industry_code":"26",  "industry_name":"化学原料和化学制品制造业"},
    {"industry_code":"261", "industry_name":"基础化学原料制造"},
    {"industry_code":"2611","industry_name":"无机酸制造"},
    {"industry_code":"2612","industry_name":"无机碱制造"},
    {"industry_code":"2613","industry_name":"无机盐制造"},
    {"industry_code":"2614","industry_name":"有机化学原料制造"},
    {"industry_code":"2619","industry_name":"其他基础化学原料制造"},
    {"industry_code":"262", "industry_name":"肥料制造"},
    {"industry_code":"2621","industry_name":"氮肥制造"},
    {"industry_code":"2622","industry_name":"磷肥制造"},
    {"industry_code":"2623","industry_name":"钾肥制造"},
    {"industry_code":"2624","industry_name":"复混肥料制造"},
    {"industry_code":"2625","industry_name":"有机肥料及微生物肥料制造"},
    {"industry_code":"2629","industry_name":"其他肥料制造"},
    {"industry_code":"263", "industry_name":"农药制造"},
    {"industry_code":"2631","industry_name":"化学农药制造"},
    {"industry_code":"2632","industry_name":"生物化学农药及微生物农药制造"},
    {"industry_code":"264", "industry_name":"涂料、油墨、颜料及类似产品制造"},
    {"industry_code":"2641","industry_name":"涂料制造"},
    {"industry_code":"2642","industry_name":"油墨及类似产品制造"},
    {"industry_code":"2643","industry_name":"颜料制造"},
    {"industry_code":"2644","industry_name":"染料制造"},
    {"industry_code":"2645","industry_name":"密封用填料及类似品制造"},
    {"industry_code":"265", "industry_name":"合成材料制造"},
    {"industry_code":"2651","industry_name":"初级形态塑料及合成树脂制造"},
    {"industry_code":"2652","industry_name":"合成橡胶制造"},
    {"industry_code":"2653","industry_name":"合成纤维单（聚合）体制造"},
    {"industry_code":"2659","industry_name":"其他合成材料制造"},
    {"industry_code":"266", "industry_name":"专用化学产品制造"},
    {"industry_code":"2661","industry_name":"化学试剂和助剂制造"},
    {"industry_code":"2662","industry_name":"专项化学用品制造"},
    {"industry_code":"2663","industry_name":"林产化学产品制造"},
    {"industry_code":"2664","industry_name":"信息化学品制造"},
    {"industry_code":"2665","industry_name":"环境污染处理专用药剂材料制造"},
    {"industry_code":"2666","industry_name":"动物胶制造"},
    {"industry_code":"2669","industry_name":"其他专用化学产品制造"},
    {"industry_code":"267", "industry_name":"炸药、火工及焰火产品制造"},
    {"industry_code":"2671","industry_name":"炸药及火工产品制造"},
    {"industry_code":"2672","industry_name":"焰火、鞭炮产品制造"},
    {"industry_code":"268", "industry_name":"日用化学产品制造"},
    {"industry_code":"2681","industry_name":"肥皂及合成洗涤剂制造"},
    {"industry_code":"2682","industry_name":"化妆品制造"},
    {"industry_code":"2683","industry_name":"口腔清洁用品制造"},
    {"industry_code":"2684","industry_name":"香料、香精制造"},
    {"industry_code":"2689","industry_name":"其他日用化学产品制造"},
    {"industry_code":"27",  "industry_name":"医药制造业"},
    {"industry_code":"271", "industry_name":"化学药品原料药制造"},
    {"industry_code":"2710","industry_name":"化学药品原料药制造"},
    {"industry_code":"272", "industry_name":"化学药品制剂制造"},
    {"industry_code":"2720","industry_name":"化学药品制剂制造"},
    {"industry_code":"273", "industry_name":"中药饮片加工"},
    {"industry_code":"2730","industry_name":"中药饮片加工"},
    {"industry_code":"274", "industry_name":"中成药生产"},
    {"industry_code":"2740","industry_name":"中成药生产"},
    {"industry_code":"275", "industry_name":"兽用药品制造"},
    {"industry_code":"2750","industry_name":"兽用药品制造"},
    {"industry_code":"276", "industry_name":"生物药品制造"},
    {"industry_code":"2760","industry_name":"生物药品制造"},
    {"industry_code":"277", "industry_name":"卫生材料及医药用品制造"},
    {"industry_code":"2770","industry_name":"卫生材料及医药用品制造"},
    {"industry_code":"28",  "industry_name":"化学纤维制造业"},
    {"industry_code":"281", "industry_name":"纤维素纤维原料及纤维制造"},
    {"industry_code":"2811","industry_name":"化纤浆粕制造"},
    {"industry_code":"2812","industry_name":"人造纤维（纤维素纤维）制造"},
    {"industry_code":"282", "industry_name":"合成纤维制造"},
    {"industry_code":"2821","industry_name":"锦纶纤维制造"},
    {"industry_code":"2822","industry_name":"涤纶纤维制造"},
    {"industry_code":"2823","industry_name":"腈纶纤维制造"},
    {"industry_code":"2824","industry_name":"维纶纤维制造"},
    {"industry_code":"2825","industry_name":"丙纶纤维制造"},
    {"industry_code":"2826","industry_name":"氨纶纤维制造"},
    {"industry_code":"2829","industry_name":"其他合成纤维制造"},
    {"industry_code":"29",  "industry_name":"橡胶和塑料制品业"},
    {"industry_code":"291", "industry_name":"橡胶制品业"},
    {"industry_code":"2911","industry_name":"轮胎制造"},
    {"industry_code":"2912","industry_name":"橡胶板、管、带制造"},
    {"industry_code":"2913","industry_name":"橡胶零件制造"},
    {"industry_code":"2914","industry_name":"再生橡胶制造"},
    {"industry_code":"2915","industry_name":"日用及医用橡胶制品制造"},
    {"industry_code":"2919","industry_name":"其他橡胶制品制造"},
    {"industry_code":"292", "industry_name":"塑料制品业"},
    {"industry_code":"2921","industry_name":"塑料薄膜制造"},
    {"industry_code":"2922","industry_name":"塑料板、管、型材制造"},
    {"industry_code":"2923","industry_name":"塑料丝、绳及编织品制造"},
    {"industry_code":"2924","industry_name":"泡沫塑料制造"},
    {"industry_code":"2925","industry_name":"塑料人造革、合成革制造"},
    {"industry_code":"2926","industry_name":"塑料包装箱及容器制造"},
    {"industry_code":"2927","industry_name":"日用塑料制品制造"},
    {"industry_code":"2928","industry_name":"塑料零件制造"},
    {"industry_code":"2929","industry_name":"其他塑料制品制造"},
    {"industry_code":"30",  "industry_name":"非金属矿物制品业"},
    {"industry_code":"301", "industry_name":"水泥、石灰和石膏制造"},
    {"industry_code":"3011","industry_name":"水泥制造"},
    {"industry_code":"3012","industry_name":"石灰和石膏制造"},
    {"industry_code":"302", "industry_name":"石膏、水泥制品及类似制品制造"},
    {"industry_code":"3021","industry_name":"水泥制品制造"},
    {"industry_code":"3022","industry_name":"砼结构构件制造"},
    {"industry_code":"3023","industry_name":"石棉水泥制品制造"},
    {"industry_code":"3024","industry_name":"轻质建筑材料制造"},
    {"industry_code":"3029","industry_name":"其他水泥类似制品制造"},
    {"industry_code":"303", "industry_name":"砖瓦、石材等建筑材料制造"},
    {"industry_code":"3031","industry_name":"粘土砖瓦及建筑砌块制造"},
    {"industry_code":"3032","industry_name":"建筑陶瓷制品制造"},
    {"industry_code":"3033","industry_name":"建筑用石加工"},
    {"industry_code":"3034","industry_name":"防水建筑材料制造"},
    {"industry_code":"3035","industry_name":"隔热和隔音材料制造"},
    {"industry_code":"3039","industry_name":"其他建筑材料制造"},
    {"industry_code":"304", "industry_name":"玻璃制造"},
    {"industry_code":"3041","industry_name":"平板玻璃制造"},
    {"industry_code":"3049","industry_name":"其他玻璃制造"},
    {"industry_code":"305", "industry_name":"玻璃制品制造"},
    {"industry_code":"3051","industry_name":"技术玻璃制品制造"},
    {"industry_code":"3052","industry_name":"光学玻璃制造"},
    {"industry_code":"3053","industry_name":"玻璃仪器制造"},
    {"industry_code":"3054","industry_name":"日用玻璃制品制造"},
    {"industry_code":"3055","industry_name":"玻璃包装容器制造"},
    {"industry_code":"3056","industry_name":"玻璃保温容器制造"},
    {"industry_code":"3057","industry_name":"制镜及类似品加工"},
    {"industry_code":"3039","industry_name":"其他玻璃制品制造"},
    {"industry_code":"306", "industry_name":"玻璃纤维和玻璃纤维增强塑料制品制造"},
    {"industry_code":"3061","industry_name":"玻璃纤维及制品制造"},
    {"industry_code":"3062","industry_name":"玻璃纤维增强塑料制品制造"},
    {"industry_code":"307", "industry_name":"陶瓷制品制造"},
    {"industry_code":"3071","industry_name":"卫生陶瓷制品制造"},
    {"industry_code":"3072","industry_name":"特种陶瓷制品制造"},
    {"industry_code":"3073","industry_name":"日用陶瓷制品制造"},
    {"industry_code":"3079","industry_name":"园林、陈设艺术及其他陶瓷制品制造"},
    {"industry_code":"308", "industry_name":"耐火材料制品制造"},
    {"industry_code":"3081","industry_name":"石棉制品制造"},
    {"industry_code":"3082","industry_name":"云母制品制造"},
    {"industry_code":"3089","industry_name":"耐火陶瓷制品及其他耐火材料制造"},
    {"industry_code":"309", "industry_name":"石墨及其他非金属矿物制品制造"},
    {"industry_code":"3091","industry_name":"石墨及碳素制品制造"},
    {"industry_code":"3099","industry_name":"其他非金属矿物制品制造"},
    {"industry_code":"31",  "industry_name":"黑色金属冶炼和压延加工业"},
    {"industry_code":"311", "industry_name":"炼铁"},
    {"industry_code":"3110","industry_name":"炼铁"},
    {"industry_code":"312", "industry_name":"炼钢"},
    {"industry_code":"3120","industry_name":"炼钢"},
    {"industry_code":"313", "industry_name":"黑色金属铸造"},
    {"industry_code":"3130","industry_name":"黑色金属铸造"},
    {"industry_code":"314", "industry_name":"钢压延加工"},
    {"industry_code":"3140","industry_name":"钢压延加工"},
    {"industry_code":"315", "industry_name":"铁合金冶炼"},
    {"industry_code":"3150","industry_name":"铁合金冶炼"},
    {"industry_code":"32",  "industry_name":"有色金属冶炼和压延加工业"},
    {"industry_code":"321", "industry_name":"常用有色金属冶炼"},
    {"industry_code":"3211","industry_name":"铜冶炼"},
    {"industry_code":"3212","industry_name":"铅锌冶炼"},
    {"industry_code":"3213","industry_name":"镍钴冶炼"},
    {"industry_code":"3214","industry_name":"锡冶炼"},
    {"industry_code":"3215","industry_name":"锑冶炼"},
    {"industry_code":"3216","industry_name":"铝冶炼"},
    {"industry_code":"3217","industry_name":"镁冶炼"},
    {"industry_code":"3219","industry_name":"其他常用有色金属冶炼"},
    {"industry_code":"322", "industry_name":"贵金属冶炼"},
    {"industry_code":"3221","industry_name":"金冶炼"},
    {"industry_code":"3222","industry_name":"银冶炼"},
    {"industry_code":"3229","industry_name":"其他贵金属冶炼"},
    {"industry_code":"323", "industry_name":"稀有稀土金属冶炼"},
    {"industry_code":"3231","industry_name":"钨钼冶炼"},
    {"industry_code":"3232","industry_name":"稀土金属冶炼"},
    {"industry_code":"3239","industry_name":"其他稀有金属冶炼"},
    {"industry_code":"324", "industry_name":"有色金属合金制造"},
    {"industry_code":"3240","industry_name":"有色金属合金制造"},
    {"industry_code":"325", "industry_name":"有色金属铸造"},
    {"industry_code":"3250","industry_name":"有色金属铸造"},
    {"industry_code":"326", "industry_name":"有色金属压延加工"},
    {"industry_code":"3261","industry_name":"铜压延加工"},
    {"industry_code":"3262","industry_name":"铝压延加工"},
    {"industry_code":"3263","industry_name":"贵金属压延加工"},
    {"industry_code":"3264","industry_name":"稀有稀土金属压延加工"},
    {"industry_code":"3269","industry_name":"其他有色金属压延加工"},
    {"industry_code":"33",  "industry_name":"金属制品业"},
    {"industry_code":"331", "industry_name":"结构性金属制品制造"},
    {"industry_code":"3311","industry_name":"金属结构制造"},
    {"industry_code":"3312","industry_name":"金属门窗制造"},
    {"industry_code":"332", "industry_name":"金属工具制造"},
    {"industry_code":"3321","industry_name":"切削工具制造"},
    {"industry_code":"3322","industry_name":"手工具制造"},
    {"industry_code":"3323","industry_name":"农用及园林用金属工具制造"},
    {"industry_code":"3324","industry_name":"刀剪及类似日用金属工具制造"},
    {"industry_code":"3329","industry_name":"其他金属工具制造"},
    {"industry_code":"333", "industry_name":"集装箱及金属包装容器制造"},
    {"industry_code":"3331","industry_name":"集装箱制造"},
    {"industry_code":"3332","industry_name":"金属压力容器制造"},
    {"industry_code":"3333","industry_name":"金属包装容器制造"},
    {"industry_code":"334", "industry_name":"金属丝绳及其制品制造"},
    {"industry_code":"3340","industry_name":"金属丝绳及其制品制造"},
    {"industry_code":"335", "industry_name":"建筑、安全用金属制品制造"},
    {"industry_code":"3351","industry_name":"建筑、家具用金属配件制造"},
    {"industry_code":"3352","industry_name":"建筑装饰及水暖管道零件制造"},
    {"industry_code":"3353","industry_name":"安全、消防用金属制品制造"},
    {"industry_code":"3359","industry_name":"其他建筑、安全用金属制品制造"},
    {"industry_code":"336", "industry_name":"金属表面处理及热处理加工"},
    {"industry_code":"3360","industry_name":"金属表面处理及热处理加工"},
    {"industry_code":"337", "industry_name":"搪瓷制品制造"},
    {"industry_code":"3371","industry_name":"生产专用搪瓷制品制造"},
    {"industry_code":"3372","industry_name":"建筑装饰搪瓷制品制造"},
    {"industry_code":"3373","industry_name":"搪瓷卫生洁具制造"},
    {"industry_code":"3379","industry_name":"搪瓷日用品及其他搪瓷制品制造"},
    {"industry_code":"338", "industry_name":"金属制日用品制造"},
    {"industry_code":"3381","industry_name":"金属制厨房用器具制造"},
    {"industry_code":"3382","industry_name":"金属制餐具和器皿制造"},
    {"industry_code":"3383","industry_name":"金属制卫生器具制造"},
    {"industry_code":"3389","industry_name":"其他金属制日用品制造"},
    {"industry_code":"339", "industry_name":"其他金属制品制造"},
    {"industry_code":"3391","industry_name":"锻件及粉末冶金制品制造"},
    {"industry_code":"3392","industry_name":"交通及公共管理用金属标牌制造"},
    {"industry_code":"3399","industry_name":"其他未列明金属制品制造"},
    {"industry_code":"34",  "industry_name":"通用设备制造业"},
    {"industry_code":"341", "industry_name":"锅炉及原动设备制造"},
    {"industry_code":"3411","industry_name":"锅炉及辅助设备制造"},
    {"industry_code":"3412","industry_name":"内燃机及配件制造"},
    {"industry_code":"3413","industry_name":"汽轮机及辅机制造"},
    {"industry_code":"3414","industry_name":"水轮机及辅机制造"},
    {"industry_code":"3415","industry_name":"风能原动设备制造"},
    {"industry_code":"3419","industry_name":"其他原动设备制造"},
    {"industry_code":"342", "industry_name":"金属加工机械制造"},
    {"industry_code":"3421","industry_name":"金属切削机床制造"},
    {"industry_code":"3422","industry_name":"金属成形机床制造"},
    {"industry_code":"3423","industry_name":"铸造机械制造"},
    {"industry_code":"3424","industry_name":"金属切割及焊接设备制造"},
    {"industry_code":"3425","industry_name":"机床附件制造"},
    {"industry_code":"3429","industry_name":"其他金属加工机械制造"},
    {"industry_code":"343", "industry_name":"物料搬运设备制造"},
    {"industry_code":"3431","industry_name":"轻小型起重设备制造"},
    {"industry_code":"3432","industry_name":"起重机制造"},
    {"industry_code":"3433","industry_name":"生产专用车辆制造"},
    {"industry_code":"3434","industry_name":"连续搬运设备制造"},
    {"industry_code":"3435","industry_name":"电梯、自动扶梯及升降机制造"},
    {"industry_code":"3439","industry_name":"其他物料搬运设备制造"},
    {"industry_code":"344", "industry_name":"泵、阀门、压缩机及类似机械制造"},
    {"industry_code":"3441","industry_name":"泵及真空设备制造"},
    {"industry_code":"3442","industry_name":"气体压缩机械制造"},
    {"industry_code":"3443","industry_name":"阀门和旋塞制造"},
    {"industry_code":"3444","industry_name":"液压和气压动力机械及元件制造"},
    {"industry_code":"345", "industry_name":"轴承、齿轮和传动部件制造"},
    {"industry_code":"3451","industry_name":"轴承制造"},
    {"industry_code":"3452","industry_name":"齿轮及齿轮减、变速箱制造"},
    {"industry_code":"3459","industry_name":"其他传动部件制造"},
    {"industry_code":"346", "industry_name":"烘炉、风机、衡器、包装等设备制造"},
    {"industry_code":"3461","industry_name":"烘炉、熔炉及电炉制造"},
    {"industry_code":"3462","industry_name":"风机、风扇制造"},
    {"industry_code":"3463","industry_name":"气体、液体分离及纯净设备制造"},
    {"industry_code":"3464","industry_name":"制冷、空调设备制造"},
    {"industry_code":"3465","industry_name":"风动和电动工具制造"},
    {"industry_code":"3466","industry_name":"喷枪及类似器具制造"},
    {"industry_code":"3467","industry_name":"衡器制造"},
    {"industry_code":"3468","industry_name":"包装专用设备制造"},
    {"industry_code":"347", "industry_name":"文化、办公用机械制造"},
    {"industry_code":"3471","industry_name":"电影机械制造"},
    {"industry_code":"3472","industry_name":"幻灯及投影设备制造"},
    {"industry_code":"3473","industry_name":"照相机及器材制造"},
    {"industry_code":"3474","industry_name":"复印和胶印设备制造"},
    {"industry_code":"3475","industry_name":"计算器及货币专用设备制造"},
    {"industry_code":"3479","industry_name":"其他文化、办公用机械制造"},
    {"industry_code":"348", "industry_name":"通用零部件制造"},
    {"industry_code":"3481","industry_name":"金属密封件制造"},
    {"industry_code":"3482","industry_name":"紧固件制造"},
    {"industry_code":"3483","industry_name":"弹簧制造"},
    {"industry_code":"3484","industry_name":"机械零部件加工"},
    {"industry_code":"3489","industry_name":"其他通用零部件制造"},
    {"industry_code":"349", "industry_name":"其他通用设备制造业"},
    {"industry_code":"3490","industry_name":"其他通用设备制造业"},
    {"industry_code":"35",  "industry_name":"专用设备制造业"},
    {"industry_code":"351", "industry_name":"采矿、冶金、建筑专用设备制造"},
    {"industry_code":"3511","industry_name":"矿山机械制造"},
    {"industry_code":"3512","industry_name":"石油钻采专用设备制造"},
    {"industry_code":"3513","industry_name":"建筑工程用机械制造"},
    {"industry_code":"3514","industry_name":"海洋工程专用设备制造"},
    {"industry_code":"3515","industry_name":"建筑材料生产专用机械制造"},
    {"industry_code":"3516","industry_name":"冶金专用设备制造"},
    {"industry_code":"352", "industry_name":"化工、木材、非金属加工专用设备制造"},
    {"industry_code":"3521","industry_name":"炼油、化工生产专用设备制造"},
    {"industry_code":"3522","industry_name":"橡胶加工专用设备制造"},
    {"industry_code":"3523","industry_name":"塑料加工专用设备制造"},
    {"industry_code":"3524","industry_name":"木材加工机械制造"},
    {"industry_code":"3525","industry_name":"模具制造"},
    {"industry_code":"3529","industry_name":"其他非金属加工专用设备制造"},
    {"industry_code":"353", "industry_name":"食品、饮料、烟草及饲料生产专用设备制造"},
    {"industry_code":"3531","industry_name":"食品、酒、饮料及茶生产专用设备制造"},
    {"industry_code":"3532","industry_name":"农副食品加工专用设备制造"},
    {"industry_code":"3533","industry_name":"烟草生产专用设备制造"},
    {"industry_code":"3534","industry_name":"饲料生产专用设备制造"},
    {"industry_code":"354", "industry_name":"印刷、制药、日化及日用品生产专用设备制造"},
    {"industry_code":"3541","industry_name":"制浆和造纸专用设备制造"},
    {"industry_code":"3542","industry_name":"印刷专用设备制造"},
    {"industry_code":"3543","industry_name":"日用化工专用设备制造"},
    {"industry_code":"3544","industry_name":"制药专用设备制造"},
    {"industry_code":"3545","industry_name":"照明器具生产专用设备制造"},
    {"industry_code":"3546","industry_name":"玻璃、陶瓷和搪瓷制品生产专用设备制造"},
    {"industry_code":"3549","industry_name":"其他日用品生产专用设备制造"},
    {"industry_code":"355", "industry_name":"纺织、服装和皮革加工专用设备制造"},
    {"industry_code":"3551","industry_name":"纺织专用设备制造"},
    {"industry_code":"3552","industry_name":"皮革、毛皮及其制品加工专用设备制造"},
    {"industry_code":"3553","industry_name":"缝制机械制造"},
    {"industry_code":"3554","industry_name":"洗涤机械制造"},
    {"industry_code":"356", "industry_name":"电子和电工机械专用设备制造"},
    {"industry_code":"3561","industry_name":"电工机械专用设备制造"},
    {"industry_code":"3562","industry_name":"电子工业专用设备制造"},
    {"industry_code":"357", "industry_name":"农、林、牧、渔专用机械制造"},
    {"industry_code":"3571","industry_name":"拖拉机制造"},
    {"industry_code":"3572","industry_name":"机械化农业及园艺机具制造"},
    {"industry_code":"3573","industry_name":"营林及木竹采伐机械制造"},
    {"industry_code":"3574","industry_name":"畜牧机械制造"},
    {"industry_code":"3575","industry_name":"渔业机械制造"},
    {"industry_code":"3576","industry_name":"农林牧渔机械配件制造"},
    {"industry_code":"3577","industry_name":"棉花加工机械制造"},
    {"industry_code":"3579","industry_name":"其他农、林、牧、渔业机械制造"},
    {"industry_code":"358", "industry_name":"医疗仪器设备及器械制造"},
    {"industry_code":"3581","industry_name":"医疗诊断、监护及治疗设备制造"},
    {"industry_code":"3582","industry_name":"口腔科用设备及器具制造"},
    {"industry_code":"3583","industry_name":"医疗实验室及医用消毒设备和器具制造"},
    {"industry_code":"3584","industry_name":"医疗、外科及兽医用器械制造"},
    {"industry_code":"3585","industry_name":"机械治疗及病房护理设备制造"},
    {"industry_code":"3586","industry_name":"假肢、人工器官及植（介）入器械制造"},
    {"industry_code":"3589","industry_name":"其他医疗设备及器械制造"},
    {"industry_code":"359", "industry_name":"环保、社会公共服务及其他专用设备制造"},
    {"industry_code":"3591","industry_name":"环境保护专用设备制造"},
    {"industry_code":"3592","industry_name":"地质勘查专用设备制造"},
    {"industry_code":"3593","industry_name":"邮政专用机械及器材制造"},
    {"industry_code":"3594","industry_name":"商业、饮食、服务专用设备制造"},
    {"industry_code":"3595","industry_name":"社会公共安全设备及器材制造"},
    {"industry_code":"3596","industry_name":"交通安全、管制及类似专用设备制造"},
    {"industry_code":"3597","industry_name":"水资源专用机械制造"},
    {"industry_code":"3599","industry_name":"其他专用设备制造"},
    {"industry_code":"36",  "industry_name":"汽车制造业"},
    {"industry_code":"361", "industry_name":"汽车整车制造"},
    {"industry_code":"3610","industry_name":"汽车整车制造"},
    {"industry_code":"362", "industry_name":"改装汽车制造"},
    {"industry_code":"3620","industry_name":"改装汽车制造"},
    {"industry_code":"363", "industry_name":"低速载货汽车制造"},
    {"industry_code":"3630","industry_name":"低速载货汽车制造"},
    {"industry_code":"364", "industry_name":"电车制造"},
    {"industry_code":"3640","industry_name":"电车制造"},
    {"industry_code":"365", "industry_name":"汽车车身、挂车制造"},
    {"industry_code":"3650","industry_name":"汽车车身、挂车制造"},
    {"industry_code":"366", "industry_name":"汽车零部件及配件制造"},
    {"industry_code":"3660","industry_name":"汽车零部件及配件制造"},
    {"industry_code":"37",  "industry_name":"铁路、船舶、航空航天和其他运输设备制造业"},
    {"industry_code":"371", "industry_name":"铁路运输设备制造"},
    {"industry_code":"3711","industry_name":"铁路机车车辆及动车组制造"},
    {"industry_code":"3712","industry_name":"窄轨机车车辆制造"},
    {"industry_code":"3713","industry_name":"铁路机车车辆配件制造"},
    {"industry_code":"3714","industry_name":"铁路专用设备及器材、配件制造"},
    {"industry_code":"3719","industry_name":"其他铁路运输设备制造"},
    {"industry_code":"372", "industry_name":"城市轨道交通设备制造"},
    {"industry_code":"3720","industry_name":"城市轨道交通设备制造"},
    {"industry_code":"373", "industry_name":"船舶及相关装置制造"},
    {"industry_code":"3731","industry_name":"金属船舶制造"},
    {"industry_code":"3732","industry_name":"非金属船舶制造"},
    {"industry_code":"3733","industry_name":"娱乐船和运动船制造"},
    {"industry_code":"3734","industry_name":"船用配套设备制造"},
    {"industry_code":"3735","industry_name":"船舶改装与拆除"},
    {"industry_code":"3739","industry_name":"航标器材及其他相关装置制造"},
    {"industry_code":"374", "industry_name":"航空、航天器及设备制造"},
    {"industry_code":"3741","industry_name":"飞机制造"},
    {"industry_code":"3742","industry_name":"航天器制造"},
    {"industry_code":"3743","industry_name":"航空、航天相关设备制造"},
    {"industry_code":"3749","industry_name":"其他航空航天器制造"},
    {"industry_code":"375", "industry_name":"摩托车制造"},
    {"industry_code":"3751","industry_name":"摩托车整车制造"},
    {"industry_code":"3752","industry_name":"摩托车零部件及配件制造"},
    {"industry_code":"376", "industry_name":"自行车制造"},
    {"industry_code":"3761","industry_name":"脚踏自行车及残疾人座车制造"},
    {"industry_code":"3762","industry_name":"助动自行车制造"},
    {"industry_code":"377", "industry_name":"非公路休闲车及零配件制造"},
    {"industry_code":"3770","industry_name":"非公路休闲车及零配件制造"},
    {"industry_code":"379", "industry_name":"潜水救捞及其他未列明运输设备制造"},
    {"industry_code":"3791","industry_name":"潜水及水下救捞装备制造"},
    {"industry_code":"3799","industry_name":"其他未列明运输设备制造"},
    {"industry_code":"38",  "industry_name":"电气机械和器材制造业"},
    {"industry_code":"381", "industry_name":"电机制造"},
    {"industry_code":"3811","industry_name":"发电机及发电机组制造"},
    {"industry_code":"3812","industry_name":"电动机制造"},
    {"industry_code":"3819","industry_name":"微电机及其他电机制造"},
    {"industry_code":"382", "industry_name":"输配电及控制设备制造"},
    {"industry_code":"3821","industry_name":"变压器、整流器和电感器"},
    {"industry_code":"3822","industry_name":"电容器及其配套设备制造"},
    {"industry_code":"3823","industry_name":"配电开关控制设备制造"},
    {"industry_code":"3824","industry_name":"电力电子元器件制造"},
    {"industry_code":"3825","industry_name":"光伏设备及元器件制造"},
    {"industry_code":"3829","industry_name":"其他输配电及控制设备制造"},
    {"industry_code":"383", "industry_name":"电线、电缆、光缆及电工器材制造"},
    {"industry_code":"3831","industry_name":"电线、电缆制造"},
    {"industry_code":"3832","industry_name":"光纤、光缆制造"},
    {"industry_code":"3833","industry_name":"绝缘制品制造"},
    {"industry_code":"3839","industry_name":"其他电工器材制造"},
    {"industry_code":"384", "industry_name":"电池制造"},
    {"industry_code":"3841","industry_name":"锂离子电池制造"},
    {"industry_code":"3842","industry_name":"镍氢电池制造"},
    {"industry_code":"3849","industry_name":"其他电池制造"},
    {"industry_code":"385", "industry_name":"家用电力器具制造"},
    {"industry_code":"3851","industry_name":"家用制冷电器具制造"},
    {"industry_code":"3852","industry_name":"家用空气调节器制造"},
    {"industry_code":"3853","industry_name":"家用通风电器具制造"},
    {"industry_code":"3854","industry_name":"家用厨房电器具制造"},
    {"industry_code":"3855","industry_name":"家用清洁卫生电器具制造"},
    {"industry_code":"3856","industry_name":"家用美容、保健电器具制造"},
    {"industry_code":"3857","industry_name":"家用电力器具专用配件制造"},
    {"industry_code":"3859","industry_name":"其他家用电力器具制造"},
    {"industry_code":"386", "industry_name":"非电力家用器具制造"},
    {"industry_code":"3861","industry_name":"燃气、太阳能及类似能源家用器具制造"},
    {"industry_code":"3869","industry_name":"其他非电力家用器具制造"},
    {"industry_code":"387", "industry_name":"照明器具制造"},
    {"industry_code":"3871","industry_name":"电光源制造"},
    {"industry_code":"3872","industry_name":"照明灯具制造"},
    {"industry_code":"3879","industry_name":"灯用电器附件及其他照明器具制造"},
    {"industry_code":"389", "industry_name":"其他电气机械及器材制造"},
    {"industry_code":"3891","industry_name":"电气信号设备装置制造"},
    {"industry_code":"3899","industry_name":"其他未列明电气机械及器材制造"},
    {"industry_code":"39",  "industry_name":"计算机、通信和其他电子设备制造业"},
    {"industry_code":"391", "industry_name":"计算机制造"},
    {"industry_code":"3911","industry_name":"计算机整机制造"},
    {"industry_code":"3912","industry_name":"计算机零部件制造"},
    {"industry_code":"3913","industry_name":"计算机外围设备制造"},
    {"industry_code":"3919","industry_name":"其他计算机制造"},
    {"industry_code":"392", "industry_name":"通信设备制造"},
    {"industry_code":"3921","industry_name":"通信系统设备制造"},
    {"industry_code":"3922","industry_name":"通信终端设备制造"},
    {"industry_code":"393", "industry_name":"广播电视设备制造"},
    {"industry_code":"3931","industry_name":"广播电视节目制作及发射设备制造"},
    {"industry_code":"3932","industry_name":"广播电视接收设备及器材制造"},
    {"industry_code":"3939","industry_name":"应用电视设备及其他广播电视设备制造"},
    {"industry_code":"394", "industry_name":"雷达及配套设备制造"},
    {"industry_code":"3940","industry_name":"雷达及配套设备制造"},
    {"industry_code":"395", "industry_name":"视听设备制造"},
    {"industry_code":"3951","industry_name":"电视机制造"},
    {"industry_code":"3952","industry_name":"音响设备制造"},
    {"industry_code":"3953","industry_name":"影视录放设备制造"},
    {"industry_code":"396", "industry_name":"电子器件制造"},
    {"industry_code":"3961","industry_name":"电子真空器件制造"},
    {"industry_code":"3962","industry_name":"半导体分立器件制造"},
    {"industry_code":"3963","industry_name":"集成电路制造"},
    {"industry_code":"3969","industry_name":"光电子器件及其他电子器件制造"},
    {"industry_code":"397", "industry_name":"电子元件制造"},
    {"industry_code":"3971","industry_name":"电子元件及组件制造"},
    {"industry_code":"3972","industry_name":"印制电路板制造"},
    {"industry_code":"399", "industry_name":"其他电子设备制造"},
    {"industry_code":"3990","industry_name":"其他电子设备制造"},
    {"industry_code":"40",  "industry_name":"仪器仪表制造业"},
    {"industry_code":"401", "industry_name":"通用仪器仪表制造"},
    {"industry_code":"4011","industry_name":"工业自动控制系统装置制造"},
    {"industry_code":"4012","industry_name":"电工仪器仪表制造"},
    {"industry_code":"4013","industry_name":"绘图、计算及测量仪器制造"},
    {"industry_code":"4014","industry_name":"实验分析仪器制造"},
    {"industry_code":"4015","industry_name":"试验机制造"},
    {"industry_code":"4019","industry_name":"供应用仪表及其他通用仪器制造"},
    {"industry_code":"402", "industry_name":"专用仪器仪表制造"},
    {"industry_code":"4021","industry_name":"环境监测专用仪器仪表制造"},
    {"industry_code":"4022","industry_name":"运输设备及生产用计数仪表制造"},
    {"industry_code":"4023","industry_name":"导航、气象及海洋专用仪器制造"},
    {"industry_code":"4024","industry_name":"农林牧渔专用仪器仪表制造"},
    {"industry_code":"4025","industry_name":"地质勘探和地震专用仪器制造"},
    {"industry_code":"4026","industry_name":"教学专用仪器制造"},
    {"industry_code":"4027","industry_name":"核子及核辐射测量仪器制造"},
    {"industry_code":"4028","industry_name":"电子测量仪器制造"},
    {"industry_code":"4029","industry_name":"其他专用仪器制造"},
    {"industry_code":"403", "industry_name":"钟表与计时仪器制造"},
    {"industry_code":"4030","industry_name":"钟表与计时仪器制造"},
    {"industry_code":"404", "industry_name":"光学仪器及眼镜制造"},
    {"industry_code":"4041","industry_name":"光学仪器制造"},
    {"industry_code":"4042","industry_name":"眼镜制造"},
    {"industry_code":"409", "industry_name":"其他仪器仪表制造业"},
    {"industry_code":"4090","industry_name":"其他仪器仪表制造业"},
    {"industry_code":"41",  "industry_name":"其他制造业"},
    {"industry_code":"411", "industry_name":"日用杂品制造"},
    {"industry_code":"4111","industry_name":"鬃毛加工、制刷及清扫工具制造"},
    {"industry_code":"4119","industry_name":"其他日用杂品制造"},
    {"industry_code":"412", "industry_name":"煤制品制造"},
    {"industry_code":"4120","industry_name":"煤制品制造"},
    {"industry_code":"413", "industry_name":"核辐射加工"},
    {"industry_code":"4130","industry_name":"核辐射加工"},
    {"industry_code":"419", "industry_name":"其他未列明制造业"},
    {"industry_code":"4190","industry_name":"其他未列明制造业"},
    {"industry_code":"42",  "industry_name":"废弃资源综合利用业"},
    {"industry_code":"421", "industry_name":"金属废料和碎屑加工处理"},
    {"industry_code":"4210","industry_name":"金属废料和碎屑加工处理"},
    {"industry_code":"422", "industry_name":"非金属废料和碎屑加工处理"},
    {"industry_code":"4220","industry_name":"非金属废料和碎屑加工处理"},
    {"industry_code":"43",  "industry_name":"金属制品、机械和设备修理业"},
    {"industry_code":"431", "industry_name":"金属制品修理"},
    {"industry_code":"4310","industry_name":"金属制品修理"},
    {"industry_code":"432", "industry_name":"通用设备修理"},
    {"industry_code":"4320","industry_name":"通用设备修理"},
    {"industry_code":"433", "industry_name":"专用设备修理"},
    {"industry_code":"4330","industry_name":"专用设备修理"},
    {"industry_code":"434", "industry_name":"铁路、船舶、航空航天等运输设备修理"},
    {"industry_code":"4341","industry_name":"铁路运输设备修理"},
    {"industry_code":"4342","industry_name":"船舶修理"},
    {"industry_code":"4343","industry_name":"航空航天器修理"},
    {"industry_code":"4349","industry_name":"其他运输设备修理"},
    {"industry_code":"435", "industry_name":"电气设备修理"},
    {"industry_code":"4350","industry_name":"电气设备修理"},
    {"industry_code":"436", "industry_name":"仪器仪表修理"},
    {"industry_code":"4360","industry_name":"仪器仪表修理"},
    {"industry_code":"439", "industry_name":"其他机械和设备修理业"},
    {"industry_code":"4390","industry_name":"其他机械和设备修理业"},
    {"industry_code":"D",   "industry_name":"电力、热力、燃气及水生产和供应业"},
    {"industry_code":"44",  "industry_name":"电力、热力生产和供应业"},
    {"industry_code":"441", "industry_name":"电力生产"},
    {"industry_code":"4411","industry_name":"火力发电"},
    {"industry_code":"4412","industry_name":"水力发电"},
    {"industry_code":"4413","industry_name":"核力发电"},
    {"industry_code":"4414","industry_name":"风力发电"},
    {"industry_code":"4415","industry_name":"太阳能发电"},
    {"industry_code":"4419","industry_name":"其他电力生产"},
    {"industry_code":"442", "industry_name":"电力供应"},
    {"industry_code":"4420","industry_name":"电力供应"},
    {"industry_code":"443", "industry_name":"热力生产和供应"},
    {"industry_code":"4430","industry_name":"热力生产和供应"},
    {"industry_code":"45",  "industry_name":"燃气生产和供应业"},
    {"industry_code":"450", "industry_name":"燃气生产和供应业"},
    {"industry_code":"4500","industry_name":"燃气生产和供应业"},
    {"industry_code":"46",  "industry_name":"水的生产和供应业"},
    {"industry_code":"461", "industry_name":"自来水生产和供应"},
    {"industry_code":"4610","industry_name":"自来水生产和供应"},
    {"industry_code":"462", "industry_name":"污水处理及其再生利用"},
    {"industry_code":"4620","industry_name":"污水处理及其再生利用"},
    {"industry_code":"469", "industry_name":"其他水的处理、利用与分配"},
    {"industry_code":"4690","industry_name":"其他水的处理、利用与分配"},
    {"industry_code":"E",   "industry_name":"建筑业"},
    {"industry_code":"47",  "industry_name":"房屋建筑业"},
    {"industry_code":"470", "industry_name":"房屋建筑业"},
    {"industry_code":"4700","industry_name":"房屋建筑业"},
    {"industry_code":"48",  "industry_name":"土木工程建筑业"},
    {"industry_code":"481", "industry_name":"铁路、道路、隧道和桥梁工程建筑"},
    {"industry_code":"4811","industry_name":"铁路工程建筑"},
    {"industry_code":"4812","industry_name":"公路工程建筑"},
    {"industry_code":"4813","industry_name":"市政道路工程建筑"},
    {"industry_code":"4819","industry_name":"其他道路、隧道和桥梁工程建筑"},
    {"industry_code":"482", "industry_name":"水利和内河港口工程建筑"},
    {"industry_code":"4821","industry_name":"水源及供水设施工程建筑"},
    {"industry_code":"4822","industry_name":"河湖治理及防洪设施工程建筑"},
    {"industry_code":"4823","industry_name":"港口及航运设施工程建筑"},
    {"industry_code":"483", "industry_name":"海洋工程建筑"},
    {"industry_code":"4830","industry_name":"海洋工程建筑"},
    {"industry_code":"484", "industry_name":"工矿工程建筑"},
    {"industry_code":"4840","industry_name":"工矿工程建筑"},
    {"industry_code":"485", "industry_name":"架线和管道工程建筑"},
    {"industry_code":"4851","industry_name":"架线及设备工程建筑"},
    {"industry_code":"4852","industry_name":"管道工程建筑"},
    {"industry_code":"489", "industry_name":"其他土木工程建筑"},
    {"industry_code":"4890","industry_name":"其他土木工程建筑"},
    {"industry_code":"49",  "industry_name":"建筑安装业"},
    {"industry_code":"491", "industry_name":"电气安装"},
    {"industry_code":"4910","industry_name":"电气安装"},
    {"industry_code":"492", "industry_name":"管道和设备安装"},
    {"industry_code":"4920","industry_name":"管道和设备安装"},
    {"industry_code":"499", "industry_name":"其他建筑安装业"},
    {"industry_code":"4990","industry_name":"其他建筑安装业"},
    {"industry_code":"50",  "industry_name":"建筑装饰和其他建筑业"},
    {"industry_code":"501", "industry_name":"建筑装饰业"},
    {"industry_code":"5010","industry_name":"建筑装饰业"},
    {"industry_code":"502", "industry_name":"工程准备活动"},
    {"industry_code":"5021","industry_name":"建筑物拆除活动"},
    {"industry_code":"5029","industry_name":"其他工程准备活动"},
    {"industry_code":"503", "industry_name":"提供施工设备服务"},
    {"industry_code":"5030","industry_name":"提供施工设备服务"},
    {"industry_code":"509", "industry_name":"其他未列明建筑业"},
    {"industry_code":"5090","industry_name":"其他未列明建筑业"},
    {"industry_code":"F",   "industry_name":"批发和零售业"},
    {"industry_code":"51",  "industry_name":"批发业"},
    {"industry_code":"511", "industry_name":"农、林、牧产品批发"},
    {"industry_code":"5111","industry_name":"谷物、豆及薯类批发"},
    {"industry_code":"5112","industry_name":"种子批发"},
    {"industry_code":"5113","industry_name":"饲料批发"},
    {"industry_code":"5114","industry_name":"棉、麻批发"},
    {"industry_code":"5115","industry_name":"林业产品批发"},
    {"industry_code":"5116","industry_name":"牲畜批发"},
    {"industry_code":"5119","industry_name":"其他农牧产品批发"},
    {"industry_code":"512", "industry_name":"食品、饮料及烟草制品批发"},
    {"industry_code":"5121","industry_name":"米、面制品及食用油批发"},
    {"industry_code":"5122","industry_name":"糕点、糖果及糖批发"},
    {"industry_code":"5123","industry_name":"果品、蔬菜批发"},
    {"industry_code":"5124","industry_name":"肉、禽、蛋、奶及水产品批发"},
    {"industry_code":"5125","industry_name":"盐及调味品批发"},
    {"industry_code":"5126","industry_name":"营养和保健品批发"},
    {"industry_code":"5127","industry_name":"酒、饮料及茶叶批发"},
    {"industry_code":"5128","industry_name":"烟草制品批发"},
    {"industry_code":"5129","industry_name":"其他食品批发"},
    {"industry_code":"513", "industry_name":"纺织、服装及家庭用品批发"},
    {"industry_code":"5131","industry_name":"纺织品、针织品及原料批发"},
    {"industry_code":"5132","industry_name":"服装批发"},
    {"industry_code":"5133","industry_name":"鞋帽批发"},
    {"industry_code":"5134","industry_name":"化妆品及卫生用品批发"},
    {"industry_code":"5135","industry_name":"厨房、卫生间用具及日用杂货批发"},
    {"industry_code":"5136","industry_name":"灯具、装饰物品批发"},
    {"industry_code":"5137","industry_name":"家用电器批发"},
    {"industry_code":"5139","industry_name":"其他家庭用品批发"},
    {"industry_code":"514", "industry_name":"文化、体育用品及器材批发"},
    {"industry_code":"5141","industry_name":"文具用品批发"},
    {"industry_code":"5142","industry_name":"体育用品及器材批发"},
    {"industry_code":"5143","industry_name":"图书批发"},
    {"industry_code":"5144","industry_name":"报刊批发"},
    {"industry_code":"5145","industry_name":"音像制品及电子出版物批发"},
    {"industry_code":"5146","industry_name":"首饰、工艺品及收藏品批发"},
    {"industry_code":"5149","industry_name":"其他文化用品批发"},
    {"industry_code":"515", "industry_name":"医药及医疗器材批发"},
    {"industry_code":"5151","industry_name":"西药批发"},
    {"industry_code":"5152","industry_name":"中药批发"},
    {"industry_code":"5153","industry_name":"医疗用品及器材批发"},
    {"industry_code":"516", "industry_name":"矿产品、建材及化工产品批发"},
    {"industry_code":"5161","industry_name":"煤炭及制品批发"},
    {"industry_code":"5162","industry_name":"石油及制品批发"},
    {"industry_code":"5163","industry_name":"非金属矿及制品批发"},
    {"industry_code":"5164","industry_name":"金属及金属矿批发"},
    {"industry_code":"5165","industry_name":"建材批发"},
    {"industry_code":"5166","industry_name":"化肥批发"},
    {"industry_code":"5167","industry_name":"农药批发"},
    {"industry_code":"5168","industry_name":"农用薄膜批发"},
    {"industry_code":"5169","industry_name":"其他化工产品批发"},
    {"industry_code":"517", "industry_name":"机械设备、五金产品及电子产品批发"},
    {"industry_code":"5171","industry_name":"农业机械批发"},
    {"industry_code":"5172","industry_name":"汽车批发"},
    {"industry_code":"5173","industry_name":"汽车零配件批发"},
    {"industry_code":"5174","industry_name":"摩托车及零配件批发"},
    {"industry_code":"5175","industry_name":"五金产品批发"},
    {"industry_code":"5176","industry_name":"电气设备批发"},
    {"industry_code":"5177","industry_name":"计算机、软件及辅助设备批发"},
    {"industry_code":"5178","industry_name":"通讯及广播电视设备批发"},
    {"industry_code":"5179","industry_name":"其他机械设备及电子产品批发"},
    {"industry_code":"518", "industry_name":"贸易经纪与代理"},
    {"industry_code":"5181","industry_name":"贸易代理"},
    {"industry_code":"5182","industry_name":"拍卖"},
    {"industry_code":"5189","industry_name":"其他贸易经纪与代理"},
    {"industry_code":"519", "industry_name":"其他批发业"},
    {"industry_code":"5191","industry_name":"再生物资回收与批发"},
    {"industry_code":"5199","industry_name":"其他未列明批发业"},
    {"industry_code":"52",  "industry_name":"零售业"},
    {"industry_code":"521", "industry_name":"综合零售"},
    {"industry_code":"5211","industry_name":"百货零售"},
    {"industry_code":"5212","industry_name":"超级市场零售"},
    {"industry_code":"5219","industry_name":"其他综合零售"},
    {"industry_code":"522", "industry_name":"食品、饮料及烟草制品专门零售"},
    {"industry_code":"5221","industry_name":"粮油零售"},
    {"industry_code":"5222","industry_name":"糕点、面包零售"},
    {"industry_code":"5223","industry_name":"果品、蔬菜零售"},
    {"industry_code":"5224","industry_name":"肉、禽、蛋、奶及水产品零售"},
    {"industry_code":"5225","industry_name":"营养和保健品零售"},
    {"industry_code":"5226","industry_name":"酒、饮料及茶叶零售"},
    {"industry_code":"5227","industry_name":"烟草制品零售"},
    {"industry_code":"5229","industry_name":"其他食品零售"},
    {"industry_code":"523", "industry_name":"纺织、服装及日用品专门零售"},
    {"industry_code":"5231","industry_name":"纺织品及针织品零售"},
    {"industry_code":"5232","industry_name":"服装零售"},
    {"industry_code":"5233","industry_name":"鞋帽零售"},
    {"industry_code":"5234","industry_name":"化妆品及卫生用品零售"},
    {"industry_code":"5235","industry_name":"钟表、眼镜零售"},
    {"industry_code":"5236","industry_name":"箱、包零售"},
    {"industry_code":"5237","industry_name":"厨房用具及日用杂品零售"},
    {"industry_code":"5238","industry_name":"自行车零售"},
    {"industry_code":"5239","industry_name":"其他日用品零售"},
    {"industry_code":"524", "industry_name":"文化、体育用品及器材专门零售"},
    {"industry_code":"5241","industry_name":"文具用品零售"},
    {"industry_code":"5242","industry_name":"体育用品及器材零售"},
    {"industry_code":"5243","industry_name":"图书、报刊零售"},
    {"industry_code":"5244","industry_name":"音像制品及电子出版物零售"},
    {"industry_code":"5245","industry_name":"珠宝首饰零售"},
    {"industry_code":"5246","industry_name":"工艺美术品及收藏品零售"},
    {"industry_code":"5247","industry_name":"乐器零售"},
    {"industry_code":"5248","industry_name":"照相器材零售"},
    {"industry_code":"5249","industry_name":"其他文化用品零售"},
    {"industry_code":"525", "industry_name":"医药及医疗器材专门零售"},
    {"industry_code":"5251","industry_name":"药品零售"},
    {"industry_code":"5252","industry_name":"医疗用品及器材零售"},
    {"industry_code":"526", "industry_name":"汽车、摩托车、燃料及零配件专门零售"},
    {"industry_code":"5261","industry_name":"汽车零售"},
    {"industry_code":"5262","industry_name":"汽车零配件零售"},
    {"industry_code":"5263","industry_name":"摩托车及零配件零售"},
    {"industry_code":"5264","industry_name":"机动车燃料零售"},
    {"industry_code":"527", "industry_name":"家用电器及电子产品专门零售"},
    {"industry_code":"5271","industry_name":"家用视听设备零售"},
    {"industry_code":"5272","industry_name":"日用家电设备零售"},
    {"industry_code":"5273","industry_name":"计算机、软件及辅助设备零售"},
    {"industry_code":"5274","industry_name":"通信设备零售"},
    {"industry_code":"5279","industry_name":"其他电子产品零售"},
    {"industry_code":"528", "industry_name":"五金、家具及室内装饰材料专门零售"},
    {"industry_code":"5281","industry_name":"五金零售"},
    {"industry_code":"5282","industry_name":"灯具零售"},
    {"industry_code":"5283","industry_name":"家具零售"},
    {"industry_code":"5284","industry_name":"涂料零售"},
    {"industry_code":"5285","industry_name":"卫生洁具零售"},
    {"industry_code":"5286","industry_name":"木质装饰材料零售"},
    {"industry_code":"5287","industry_name":"陶瓷、石材装饰材料零售"},
    {"industry_code":"5289","industry_name":"其他室内装饰材料零售"},
    {"industry_code":"529", "industry_name":"货摊、无店铺及其他零售业"},
    {"industry_code":"5291","industry_name":"货摊食品零售"},
    {"industry_code":"5292","industry_name":"货摊纺织、服装及鞋零售"},
    {"industry_code":"5293","industry_name":"货摊日用品零售"},
    {"industry_code":"5294","industry_name":"互联网零售"},
    {"industry_code":"5295","industry_name":"邮购及电视、电话零售"},
    {"industry_code":"5296","industry_name":"旧货零售"},
    {"industry_code":"5297","industry_name":"生活用燃料零售"},
    {"industry_code":"5299","industry_name":"其他未列明零售业"},
    {"industry_code":"G",   "industry_name":"交通运输、仓储和邮政业"},
    {"industry_code":"53",  "industry_name":"铁路运输业"},
    {"industry_code":"531", "industry_name":"铁路旅客运输"},
    {"industry_code":"5310","industry_name":"铁路旅客运输"},
    {"industry_code":"532", "industry_name":"铁路货物运输"},
    {"industry_code":"5320","industry_name":"铁路货物运输"},
    {"industry_code":"533", "industry_name":"铁路运输辅助活动"},
    {"industry_code":"5331","industry_name":"客运火车站"},
    {"industry_code":"5332","industry_name":"货运火车站"},
    {"industry_code":"5339","industry_name":"其他铁路运输辅助活动"},
    {"industry_code":"54",  "industry_name":"道路运输业"},
    {"industry_code":"541", "industry_name":"城市公共交通运输"},
    {"industry_code":"5411","industry_name":"公共电汽车客运"},
    {"industry_code":"5412","industry_name":"城市轨道交通"},
    {"industry_code":"5413","industry_name":"出租车客运"},
    {"industry_code":"5419","industry_name":"其他城市公共交通运输"},
    {"industry_code":"542", "industry_name":"公路旅客运输"},
    {"industry_code":"5420","industry_name":"公路旅客运输"},
    {"industry_code":"543", "industry_name":"道路货物运输"},
    {"industry_code":"5430","industry_name":"道路货物运输"},
    {"industry_code":"544", "industry_name":"道路运输辅助活动"},
    {"industry_code":"5441","industry_name":"客运汽车站"},
    {"industry_code":"5442","industry_name":"公路管理与养护"},
    {"industry_code":"5449","industry_name":"其他道路运输辅助活动"},
    {"industry_code":"55",  "industry_name":"水上运输业"},
    {"industry_code":"551", "industry_name":"水上旅客运输"},
    {"industry_code":"5511","industry_name":"海洋旅客运输"},
    {"industry_code":"5512","industry_name":"内河旅客运输"},
    {"industry_code":"5513","industry_name":"客运轮渡运输"},
    {"industry_code":"552", "industry_name":"水上货物运输"},
    {"industry_code":"5521","industry_name":"远洋货物运输"},
    {"industry_code":"5522","industry_name":"沿海货物运输"},
    {"industry_code":"5523","industry_name":"内河货物运输"},
    {"industry_code":"553", "industry_name":"水上运输辅助活动"},
    {"industry_code":"5531","industry_name":"客运港口"},
    {"industry_code":"5532","industry_name":"货运港口"},
    {"industry_code":"5539","industry_name":"其他水上运输辅助活动"},
    {"industry_code":"56",  "industry_name":"航空运输业"},
    {"industry_code":"561", "industry_name":"航空客货运输"},
    {"industry_code":"5611","industry_name":"航空旅客运输"},
    {"industry_code":"5612","industry_name":"航空货物运输"},
    {"industry_code":"562", "industry_name":"通用航空服务"},
    {"industry_code":"5620","industry_name":"通用航空服务"},
    {"industry_code":"563", "industry_name":"航空运输辅助活动"},
    {"industry_code":"5631","industry_name":"机场"},
    {"industry_code":"5632","industry_name":"空中交通管理"},
    {"industry_code":"5639","industry_name":"其他航空运输辅助活动"},
    {"industry_code":"57",  "industry_name":"管道运输业"},
    {"industry_code":"570", "industry_name":"管道运输业"},
    {"industry_code":"5700","industry_name":"管道运输业"},
    {"industry_code":"58",  "industry_name":"装卸搬运和运输代理业"},
    {"industry_code":"581", "industry_name":"装卸搬运"},
    {"industry_code":"5810","industry_name":"装卸搬运"},
    {"industry_code":"582", "industry_name":"运输代理业"},
    {"industry_code":"5821","industry_name":"货物运输代理"},
    {"industry_code":"5822","industry_name":"旅客票务代理"},
    {"industry_code":"5829","industry_name":"其他运输代理业"},
    {"industry_code":"59",  "industry_name":"仓储业"},
    {"industry_code":"591", "industry_name":"谷物、棉花等农产品仓储"},
    {"industry_code":"5911","industry_name":"谷物仓储"},
    {"industry_code":"5912","industry_name":"棉花仓储"},
    {"industry_code":"5919","industry_name":"其他农产品仓储"},
    {"industry_code":"599", "industry_name":"其他仓储业"},
    {"industry_code":"5990","industry_name":"其他仓储业"},
    {"industry_code":"60",  "industry_name":"邮政业"},
    {"industry_code":"601", "industry_name":"邮政基本服务"},
    {"industry_code":"6010","industry_name":"邮政基本服务"},
    {"industry_code":"602", "industry_name":"快递服务"},
    {"industry_code":"6020","industry_name":"快递服务"},
    {"industry_code":"H",   "industry_name":"住宿和餐饮业"},
    {"industry_code":"61",  "industry_name":"住宿业"},
    {"industry_code":"611", "industry_name":"旅游饭店"},
    {"industry_code":"6110","industry_name":"旅游饭店"},
    {"industry_code":"612", "industry_name":"一般旅馆"},
    {"industry_code":"6120","industry_name":"一般旅馆"},
    {"industry_code":"619", "industry_name":"其他住宿业"},
    {"industry_code":"6190","industry_name":"其他住宿业"},
    {"industry_code":"62",  "industry_name":"餐饮业"},
    {"industry_code":"621", "industry_name":"正餐服务"},
    {"industry_code":"6210","industry_name":"正餐服务"},
    {"industry_code":"622", "industry_name":"快餐服务"},
    {"industry_code":"6220","industry_name":"快餐服务"},
    {"industry_code":"623", "industry_name":"饮料及冷饮服务"},
    {"industry_code":"6231","industry_name":"茶馆服务"},
    {"industry_code":"6232","industry_name":"咖啡馆服务"},
    {"industry_code":"6233","industry_name":"酒吧服务"},
    {"industry_code":"6239","industry_name":"其他饮料及冷饮服务"},
    {"industry_code":"629", "industry_name":"其他餐饮业"},
    {"industry_code":"6291","industry_name":"小吃服务"},
    {"industry_code":"6292","industry_name":"餐饮配送服务"},
    {"industry_code":"6299","industry_name":"其他未列明餐饮业"},
    {"industry_code":"I",   "industry_name":"信息传输、软件和信息技术服务业"},
    {"industry_code":"63",  "industry_name":"电信、广播电视和卫星传输服务"},
    {"industry_code":"631", "industry_name":"电信"},
    {"industry_code":"6311","industry_name":"固定电信服务"},
    {"industry_code":"6312","industry_name":"移动电信服务"},
    {"industry_code":"6319","industry_name":"其他电信服务"},
    {"industry_code":"632", "industry_name":"广播电视传输服务"},
    {"industry_code":"6321","industry_name":"有线广播电视传输服务"},
    {"industry_code":"6322","industry_name":"无线广播电视传输服务"},
    {"industry_code":"633", "industry_name":"卫星传输服务"},
    {"industry_code":"6330","industry_name":"卫星传输服务"},
    {"industry_code":"64",  "industry_name":"互联网和相关服务"},
    {"industry_code":"641", "industry_name":"互联网接入及相关服务"},
    {"industry_code":"6410","industry_name":"互联网接入及相关服务"},
    {"industry_code":"642", "industry_name":"互联网信息服务"},
    {"industry_code":"6420","industry_name":"互联网信息服务"},
    {"industry_code":"649", "industry_name":"其他互联网服务"},
    {"industry_code":"6490","industry_name":"其他互联网服务"},
    {"industry_code":"65",  "industry_name":"软件和信息技术服务业"},
    {"industry_code":"651", "industry_name":"软件开发"},
    {"industry_code":"6510","industry_name":"软件开发"},
    {"industry_code":"652", "industry_name":"信息系统集成服务"},
    {"industry_code":"6520","industry_name":"信息系统集成服务"},
    {"industry_code":"653", "industry_name":"信息技术咨询服务"},
    {"industry_code":"6530","industry_name":"信息技术咨询服务"},
    {"industry_code":"654", "industry_name":"数据处理和存储服务"},
    {"industry_code":"6540","industry_name":"数据处理和存储服务"},
    {"industry_code":"655", "industry_name":"集成电路设计"},
    {"industry_code":"6550","industry_name":"集成电路设计"},
    {"industry_code":"659", "industry_name":"其他信息技术服务业"},
    {"industry_code":"6591","industry_name":"数字内容服务"},
    {"industry_code":"6592","industry_name":"呼叫中心"},
    {"industry_code":"6599","industry_name":"其他未列明信息技术服务业"},
    {"industry_code":"J",   "industry_name":"金融业"},
    {"industry_code":"66",  "industry_name":"货币金融服务"},
    {"industry_code":"661", "industry_name":"中央银行服务"},
    {"industry_code":"6610","industry_name":"中央银行服务"},
    {"industry_code":"662", "industry_name":"货币银行服务"},
    {"industry_code":"6620","industry_name":"货币银行服务"},
    {"industry_code":"663", "industry_name":"非货币银行服务"},
    {"industry_code":"6631","industry_name":"金融租赁服务"},
    {"industry_code":"6632","industry_name":"财务公司"},
    {"industry_code":"6633","industry_name":"典当"},
    {"industry_code":"6639","industry_name":"其他非货币银行服务"},
    {"industry_code":"664", "industry_name":"银行监管服务"},
    {"industry_code":"6640","industry_name":"银行监管服务"},
    {"industry_code":"67",  "industry_name":"资本市场服务"},
    {"industry_code":"671", "industry_name":"证券市场服务"},
    {"industry_code":"6711","industry_name":"证券市场管理服务"},
    {"industry_code":"6712","industry_name":"证券经纪交易服务"},
    {"industry_code":"6713","industry_name":"基金管理服务"},
    {"industry_code":"672", "industry_name":"期货市场服务"},
    {"industry_code":"6721","industry_name":"期货市场管理服务"},
    {"industry_code":"6729","industry_name":"其他期货市场服务"},
    {"industry_code":"673", "industry_name":"证券期货监管服务"},
    {"industry_code":"6730","industry_name":"证券期货监管服务"},
    {"industry_code":"674", "industry_name":"资本投资服务"},
    {"industry_code":"6740","industry_name":"资本投资服务"},
    {"industry_code":"679", "industry_name":"其他资本市场服务"},
    {"industry_code":"6790","industry_name":"其他资本市场服务"},
    {"industry_code":"68",  "industry_name":"保险业"},
    {"industry_code":"681", "industry_name":"人身保险"},
    {"industry_code":"6811","industry_name":"人寿保险"},
    {"industry_code":"6812","industry_name":"健康和意外保险"},
    {"industry_code":"682", "industry_name":"财产保险"},
    {"industry_code":"6820","industry_name":"财产保险"},
    {"industry_code":"683", "industry_name":"再保险"},
    {"industry_code":"6830","industry_name":"再保险"},
    {"industry_code":"684", "industry_name":"养老金"},
    {"industry_code":"6840","industry_name":"养老金"},
    {"industry_code":"685", "industry_name":"保险经纪与代理服务"},
    {"industry_code":"6850","industry_name":"保险经纪与代理服务"},
    {"industry_code":"686", "industry_name":"保险监管服务"},
    {"industry_code":"6860","industry_name":"保险监管服务"},
    {"industry_code":"689", "industry_name":"其他保险活动"},
    {"industry_code":"6891","industry_name":"风险和损失评估"},
    {"industry_code":"6899","industry_name":"其他未列明保险活动"},
    {"industry_code":"69",  "industry_name":"其他金融业"},
    {"industry_code":"691", "industry_name":"金融信托与管理服务"},
    {"industry_code":"6910","industry_name":"金融信托与管理服务"},
    {"industry_code":"692", "industry_name":"控股公司服务"},
    {"industry_code":"6920","industry_name":"控股公司服务"},
    {"industry_code":"693", "industry_name":"非金融机构支付服务"},
    {"industry_code":"6930","industry_name":"非金融机构支付服务"},
    {"industry_code":"694", "industry_name":"金融信息服务"},
    {"industry_code":"6940","industry_name":"金融信息服务"},
    {"industry_code":"699", "industry_name":"其他未列明金融业"},
    {"industry_code":"6990","industry_name":"其他未列明金融业"},
    {"industry_code":"K",   "industry_name":"房地产业"},
    {"industry_code":"70",  "industry_name":"房地产业"},
    {"industry_code":"701", "industry_name":"房地产开发经营"},
    {"industry_code":"7010","industry_name":"房地产开发经营"},
    {"industry_code":"702", "industry_name":"物业管理"},
    {"industry_code":"7020","industry_name":"物业管理"},
    {"industry_code":"703", "industry_name":"房地产中介服务"},
    {"industry_code":"7030","industry_name":"房地产中介服务"},
    {"industry_code":"704", "industry_name":"自有房地产经营活动"},
    {"industry_code":"7040","industry_name":"自有房地产经营活动"},
    {"industry_code":"709", "industry_name":"其他房地产业"},
    {"industry_code":"7090","industry_name":"其他房地产业"},
    {"industry_code":"L",   "industry_name":"租赁和商务服务业"},
    {"industry_code":"71",  "industry_name":"租赁业"},
    {"industry_code":"711", "industry_name":"机械设备租赁"},
    {"industry_code":"7111","industry_name":"汽车租赁"},
    {"industry_code":"7112","industry_name":"农业机械租赁"},
    {"industry_code":"7113","industry_name":"建筑工程机械与设备租赁"},
    {"industry_code":"7114","industry_name":"计算机及通讯设备租赁"},
    {"industry_code":"7119","industry_name":"其他机械与设备租赁"},
    {"industry_code":"712", "industry_name":"文化及日用品出租"},
    {"industry_code":"7121","industry_name":"娱乐及体育设备出租"},
    {"industry_code":"7122","industry_name":"图书出租"},
    {"industry_code":"7123","industry_name":"音像制品出租"},
    {"industry_code":"7129","industry_name":"其他文化及日用品出租"},
    {"industry_code":"72",  "industry_name":"商务服务业"},
    {"industry_code":"721", "industry_name":"企业管理服务"},
    {"industry_code":"7211","industry_name":"企业总部管理"},
    {"industry_code":"7212","industry_name":"投资与资产管理"},
    {"industry_code":"7213","industry_name":"单位后勤管理服务"},
    {"industry_code":"7219","industry_name":"其他企业管理服务"},
    {"industry_code":"722", "industry_name":"法律服务"},
    {"industry_code":"7221","industry_name":"律师及相关法律服务"},
    {"industry_code":"7222","industry_name":"公证服务"},
    {"industry_code":"7229","industry_name":"其他法律服务"},
    {"industry_code":"723", "industry_name":"咨询与调查"},
    {"industry_code":"7231","industry_name":"会计、审计及税务服务"},
    {"industry_code":"7232","industry_name":"市场调查"},
    {"industry_code":"7233","industry_name":"社会经济咨询"},
    {"industry_code":"7239","industry_name":"其他专业咨询"},
    {"industry_code":"724", "industry_name":"广告业"},
    {"industry_code":"7240","industry_name":"广告业"},
    {"industry_code":"725", "industry_name":"知识产权服务"},
    {"industry_code":"7250","industry_name":"知识产权服务"},
    {"industry_code":"726", "industry_name":"人力资源服务"},
    {"industry_code":"7261","industry_name":"公共就业服务"},
    {"industry_code":"7262","industry_name":"职业中介服务"},
    {"industry_code":"7263","industry_name":"劳务派遣服务"},
    {"industry_code":"7269","industry_name":"其他人力资源服务"},
    {"industry_code":"727", "industry_name":"旅行社及相关服务"},
    {"industry_code":"7271","industry_name":"旅行社服务"},
    {"industry_code":"7272","industry_name":"旅游管理服务"},
    {"industry_code":"7279","industry_name":"其他旅行社相关服务"},
    {"industry_code":"728", "industry_name":"安全保护服务"},
    {"industry_code":"7281","industry_name":"安全服务"},
    {"industry_code":"7282","industry_name":"安全系统监控服务"},
    {"industry_code":"7289","industry_name":"其他安全保护服务"},
    {"industry_code":"729", "industry_name":"其他商务服务业"},
    {"industry_code":"7291","industry_name":"市场管理"},
    {"industry_code":"7292","industry_name":"会议及展览服务"},
    {"industry_code":"7293","industry_name":"包装服务"},
    {"industry_code":"7294","industry_name":"办公服务"},
    {"industry_code":"7295","industry_name":"信用服务"},
    {"industry_code":"7296","industry_name":"担保服务"},
    {"industry_code":"7299","industry_name":"其他未列明商务服务业"},
    {"industry_code":"M",   "industry_name":"科学研究和技术服务业"},
    {"industry_code":"73",  "industry_name":"研究和试验发展"},
    {"industry_code":"731", "industry_name":"自然科学研究和试验发展"},
    {"industry_code":"7310","industry_name":"自然科学研究和试验发展"},
    {"industry_code":"732", "industry_name":"工程和技术研究和试验发展"},
    {"industry_code":"7320","industry_name":"工程和技术研究和试验发展"},
    {"industry_code":"733", "industry_name":"农业科学研究和试验发展"},
    {"industry_code":"7330","industry_name":"农业科学研究和试验发展"},
    {"industry_code":"734", "industry_name":"医学研究和试验发展"},
    {"industry_code":"7340","industry_name":"医学研究和试验发展"},
    {"industry_code":"735", "industry_name":"社会人文科学研究"},
    {"industry_code":"7350","industry_name":"社会人文科学研究"},
    {"industry_code":"74",  "industry_name":"专业技术服务业"},
    {"industry_code":"741", "industry_name":"气象服务"},
    {"industry_code":"7410","industry_name":"气象服务"},
    {"industry_code":"742", "industry_name":"地震服务"},
    {"industry_code":"7420","industry_name":"地震服务"},
    {"industry_code":"743", "industry_name":"海洋服务"},
    {"industry_code":"7430","industry_name":"海洋服务"},
    {"industry_code":"744", "industry_name":"测绘服务"},
    {"industry_code":"7440","industry_name":"测绘服务"},
    {"industry_code":"745", "industry_name":"质检技术服务"},
    {"industry_code":"7450","industry_name":"质检技术服务"},
    {"industry_code":"746", "industry_name":"环境与生态监测"},
    {"industry_code":"7461","industry_name":"环境保护监测"},
    {"industry_code":"7462","industry_name":"生态监测"},
    {"industry_code":"747", "industry_name":"地质勘查"},
    {"industry_code":"7471","industry_name":"能源矿产地质勘查"},
    {"industry_code":"7472","industry_name":"固体矿产地质勘查"},
    {"industry_code":"7473","industry_name":"水、二氧化碳等矿产地质勘查"},
    {"industry_code":"7474","industry_name":"基础地质勘查"},
    {"industry_code":"7475","industry_name":"地质勘查技术服务"},
    {"industry_code":"748", "industry_name":"工程技术"},
    {"industry_code":"7481","industry_name":"工程管理服务"},
    {"industry_code":"7482","industry_name":"工程勘察设计"},
    {"industry_code":"7483","industry_name":"规划管理"},
    {"industry_code":"749", "industry_name":"其他专业技术服务业"},
    {"industry_code":"7491","industry_name":"专业化设计服务"},
    {"industry_code":"7492","industry_name":"摄影扩印服务"},
    {"industry_code":"7493","industry_name":"兽医服务"},
    {"industry_code":"7499","industry_name":"其他未列明专业技术服务业"},
    {"industry_code":"75",  "industry_name":"科技推广和应用服务业"},
    {"industry_code":"751", "industry_name":"技术推广服务"},
    {"industry_code":"7511","industry_name":"农业技术推广服务"},
    {"industry_code":"7512","industry_name":"生物技术推广服务"},
    {"industry_code":"7513","industry_name":"新材料技术推广服务"},
    {"industry_code":"7514","industry_name":"节能技术推广服务"},
    {"industry_code":"7519","industry_name":"其他技术推广服务"},
    {"industry_code":"752", "industry_name":"科技中介服务"},
    {"industry_code":"7520","industry_name":"科技中介服务"},
    {"industry_code":"759", "industry_name":"其他科技推广和应用服务业"},
    {"industry_code":"7590","industry_name":"其他科技推广和应用服务业"},
    {"industry_code":"N",   "industry_name":"水利、环境和公共设施管理业"},
    {"industry_code":"76",  "industry_name":"水利管理业"},
    {"industry_code":"761", "industry_name":"防洪除涝设施管理"},
    {"industry_code":"7610","industry_name":"防洪除涝设施管理"},
    {"industry_code":"762", "industry_name":"水资源管理"},
    {"industry_code":"7620","industry_name":"水资源管理"},
    {"industry_code":"763", "industry_name":"天然水收集与分配"},
    {"industry_code":"7630","industry_name":"天然水收集与分配"},
    {"industry_code":"764", "industry_name":"水文服务"},
    {"industry_code":"7640","industry_name":"水文服务"},
    {"industry_code":"769", "industry_name":"其他水利管理业"},
    {"industry_code":"7690","industry_name":"其他水利管理业"},
    {"industry_code":"77",  "industry_name":"生态保护和环境治理业"},
    {"industry_code":"771", "industry_name":"生态保护"},
    {"industry_code":"7711","industry_name":"自然保护区管理"},
    {"industry_code":"7712","industry_name":"野生动物保护"},
    {"industry_code":"7713","industry_name":"野生植物保护"},
    {"industry_code":"7719","industry_name":"其他自然保护"},
    {"industry_code":"772", "industry_name":"环境治理业"},
    {"industry_code":"7721","industry_name":"水污染治理"},
    {"industry_code":"7722","industry_name":"大气污染治理"},
    {"industry_code":"7723","industry_name":"固体废物治理"},
    {"industry_code":"7724","industry_name":"危险废物治理"},
    {"industry_code":"7725","industry_name":"放射性废物治理"},
    {"industry_code":"7729","industry_name":"其他污染治理"},
    {"industry_code":"78",  "industry_name":"公共设施管理业"},
    {"industry_code":"781", "industry_name":"市政设施管理"},
    {"industry_code":"7810","industry_name":"市政设施管理"},
    {"industry_code":"782", "industry_name":"环境卫生管理"},
    {"industry_code":"7820","industry_name":"环境卫生管理"},
    {"industry_code":"783", "industry_name":"城乡市容管理"},
    {"industry_code":"7830","industry_name":"城乡市容管理"},
    {"industry_code":"784", "industry_name":"绿化管理"},
    {"industry_code":"7840","industry_name":"绿化管理"},
    {"industry_code":"785", "industry_name":"公园和游览景区管理"},
    {"industry_code":"7851","industry_name":"公园管理"},
    {"industry_code":"7852","industry_name":"游览景区管理"},
    {"industry_code":"O",   "industry_name":"居民服务、修理和其他服务业"},
    {"industry_code":"79",  "industry_name":"居民服务业"},
    {"industry_code":"791", "industry_name":"家庭服务"},
    {"industry_code":"7910","industry_name":"家庭服务"},
    {"industry_code":"792", "industry_name":"托儿所服务"},
    {"industry_code":"7920","industry_name":"托儿所服务"},
    {"industry_code":"793", "industry_name":"洗染服务"},
    {"industry_code":"7930","industry_name":"洗染服务"},
    {"industry_code":"794", "industry_name":"理发及美容服务"},
    {"industry_code":"7940","industry_name":"理发及美容服务"},
    {"industry_code":"795", "industry_name":"洗浴服务"},
    {"industry_code":"7950","industry_name":"洗浴服务"},
    {"industry_code":"796", "industry_name":"保健服务"},
    {"industry_code":"7960","industry_name":"保健服务"},
    {"industry_code":"797", "industry_name":"婚姻服务"},
    {"industry_code":"7970","industry_name":"婚姻服务"},
    {"industry_code":"798", "industry_name":"殡葬服务"},
    {"industry_code":"7980","industry_name":"殡葬服务"},
    {"industry_code":"799", "industry_name":"其他居民服务业"},
    {"industry_code":"7990","industry_name":"其他居民服务业"},
    {"industry_code":"80",  "industry_name":"机动车、电子产品和日用产品修理业"},
    {"industry_code":"801", "industry_name":"汽车、摩托车修理与维护"},
    {"industry_code":"8011","industry_name":"汽车修理与维护"},
    {"industry_code":"8012","industry_name":"摩托车修理与维护"},
    {"industry_code":"802", "industry_name":"计算机和办公设备维修"},
    {"industry_code":"8021","industry_name":"计算机和辅助设备修理"},
    {"industry_code":"8022","industry_name":"通讯设备修理"},
    {"industry_code":"8029","industry_name":"其他办公设备维修"},
    {"industry_code":"803", "industry_name":"家用电器修理"},
    {"industry_code":"8031","industry_name":"家用电子产品修理"},
    {"industry_code":"8032","industry_name":"日用电器修理"},
    {"industry_code":"809", "industry_name":"其他日用产品修理业"},
    {"industry_code":"8091","industry_name":"自行车修理"},
    {"industry_code":"8092","industry_name":"鞋和皮革修理"},
    {"industry_code":"8093","industry_name":"家具和相关物品修理"},
    {"industry_code":"8099","industry_name":"其他未列明日用产品修理业"},
    {"industry_code":"81",  "industry_name":"其他服务业"},
    {"industry_code":"811", "industry_name":"清洁服务"},
    {"industry_code":"8111","industry_name":"建筑物清洁服务"},
    {"industry_code":"8119","industry_name":"其他清洁服务"},
    {"industry_code":"819", "industry_name":"其他未列明服务业"},
    {"industry_code":"8190","industry_name":"其他未列明服务业"},
    {"industry_code":"P",   "industry_name":"教育"},
    {"industry_code":"82",  "industry_name":"教育"},
    {"industry_code":"821", "industry_name":"学前教育"},
    {"industry_code":"8210","industry_name":"学前教育"},
    {"industry_code":"822", "industry_name":"初等教育"},
    {"industry_code":"8221","industry_name":"普通小学教育"},
    {"industry_code":"8222","industry_name":"成人小学教育"},
    {"industry_code":"823", "industry_name":"中等教育"},
    {"industry_code":"8231","industry_name":"普通初中教育"},
    {"industry_code":"8232","industry_name":"职业初中教育"},
    {"industry_code":"8233","industry_name":"成人初中教育"},
    {"industry_code":"8234","industry_name":"普通高中教育"},
    {"industry_code":"8235","industry_name":"成人高中教育"},
    {"industry_code":"8236","industry_name":"中等职业学校教育"},
    {"industry_code":"824", "industry_name":"高等教育"},
    {"industry_code":"8241","industry_name":"普通高等教育"},
    {"industry_code":"8242","industry_name":"成人高等教育"},
    {"industry_code":"825", "industry_name":"特殊教育"},
    {"industry_code":"8250","industry_name":"特殊教育"},
    {"industry_code":"829", "industry_name":"技能培训、教育辅助及其他教育"},
    {"industry_code":"8291","industry_name":"职业技能培训"},
    {"industry_code":"8292","industry_name":"体校及体育培训"},
    {"industry_code":"8293","industry_name":"文化艺术培训"},
    {"industry_code":"8294","industry_name":"教育辅助服务"},
    {"industry_code":"8299","industry_name":"其他未列明教育"},
    {"industry_code":"Q",   "industry_name":"卫生和社会工作"},
    {"industry_code":"83",  "industry_name":"卫生"},
    {"industry_code":"831", "industry_name":"医院"},
    {"industry_code":"8311","industry_name":"综合医院"},
    {"industry_code":"8312","industry_name":"中医医院"},
    {"industry_code":"8313","industry_name":"中西医结合医院"},
    {"industry_code":"8314","industry_name":"民族医院"},
    {"industry_code":"8315","industry_name":"专科医院"},
    {"industry_code":"8316","industry_name":"疗养院"},
    {"industry_code":"832", "industry_name":"社区医疗与卫生院"},
    {"industry_code":"8321","industry_name":"社区卫生服务中心（站）"},
    {"industry_code":"8322","industry_name":"街道卫生院"},
    {"industry_code":"8323","industry_name":"乡镇卫生院"},
    {"industry_code":"833", "industry_name":"门诊部（所）"},
    {"industry_code":"8330","industry_name":"门诊部（所）"},
    {"industry_code":"834", "industry_name":"计划生育技术服务活动"},
    {"industry_code":"8340","industry_name":"计划生育技术服务活动"},
    {"industry_code":"835", "industry_name":"妇幼保健院（所、站）"},
    {"industry_code":"8350","industry_name":"妇幼保健院（所、站）"},
    {"industry_code":"836", "industry_name":"专科疾病防治院（所、站）"},
    {"industry_code":"8360","industry_name":"专科疾病防治院（所、站）"},
    {"industry_code":"837", "industry_name":"疾病预防控制中心"},
    {"industry_code":"8370","industry_name":"疾病预防控制中心"},
    {"industry_code":"839", "industry_name":"其他卫生活动"},
    {"industry_code":"8390","industry_name":"其他卫生活动"},
    {"industry_code":"84",  "industry_name":"社会工作"},
    {"industry_code":"841", "industry_name":"提供住宿社会工作"},
    {"industry_code":"8411","industry_name":"干部休养所"},
    {"industry_code":"8412","industry_name":"护理机构服务"},
    {"industry_code":"8413","industry_name":"精神康复服务"},
    {"industry_code":"8414","industry_name":"老年人、残疾人养护服务"},
    {"industry_code":"8415","industry_name":"孤残儿童收养和庇护服务"},
    {"industry_code":"8419","industry_name":"其他提供住宿社会救助"},
    {"industry_code":"842", "industry_name":"不提供住宿社会工作"},
    {"industry_code":"8421","industry_name":"社会看护与帮助服务"},
    {"industry_code":"8429","industry_name":"其他不提供住宿社会工作"},
    {"industry_code":"R",   "industry_name":"文化、体育和娱乐业"},
    {"industry_code":"85",  "industry_name":"新闻和出版业"},
    {"industry_code":"851", "industry_name":"新闻业"},
    {"industry_code":"8510","industry_name":"新闻业"},
    {"industry_code":"852", "industry_name":"出版业"},
    {"industry_code":"8521","industry_name":"图书出版"},
    {"industry_code":"8522","industry_name":"报纸出版"},
    {"industry_code":"8523","industry_name":"期刊出版"},
    {"industry_code":"8524","industry_name":"音像制品出版"},
    {"industry_code":"8525","industry_name":"电子出版物出版"},
    {"industry_code":"8529","industry_name":"其他出版业"},
    {"industry_code":"86",  "industry_name":"广播、电视、电影和影视录音制作业"},
    {"industry_code":"861", "industry_name":"广播"},
    {"industry_code":"8610","industry_name":"广播"},
    {"industry_code":"862", "industry_name":"电视"},
    {"industry_code":"8620","industry_name":"电视"},
    {"industry_code":"863", "industry_name":"电影和影视节目制作"},
    {"industry_code":"8630","industry_name":"电影和影视节目制作"},
    {"industry_code":"864", "industry_name":"电影和影视节目发行"},
    {"industry_code":"8640","industry_name":"电影和影视节目发行"},
    {"industry_code":"865", "industry_name":"电影放映"},
    {"industry_code":"8650","industry_name":"电影放映"},
    {"industry_code":"866", "industry_name":"录音制作"},
    {"industry_code":"8660","industry_name":"录音制作"},
    {"industry_code":"87",  "industry_name":"文化艺术业"},
    {"industry_code":"871", "industry_name":"文艺创作与表演"},
    {"industry_code":"8710","industry_name":"文艺创作与表演"},
    {"industry_code":"872", "industry_name":"艺术表演场馆"},
    {"industry_code":"8720","industry_name":"艺术表演场馆"},
    {"industry_code":"873", "industry_name":"图书馆与档案馆"},
    {"industry_code":"8731","industry_name":"图书馆"},
    {"industry_code":"8732","industry_name":"档案馆"},
    {"industry_code":"874", "industry_name":"文物及非物质文化遗产保护"},
    {"industry_code":"8740","industry_name":"文物及非物质文化遗产保护"},
    {"industry_code":"875", "industry_name":"博物馆"},
    {"industry_code":"8750","industry_name":"博物馆"},
    {"industry_code":"876", "industry_name":"烈士陵园、纪念馆"},
    {"industry_code":"8760","industry_name":"烈士陵园、纪念馆"},
    {"industry_code":"877", "industry_name":"群众文化活动"},
    {"industry_code":"8770","industry_name":"群众文化活动"},
    {"industry_code":"879", "industry_name":"其他文化艺术业"},
    {"industry_code":"8790","industry_name":"其他文化艺术业"},
    {"industry_code":"88",  "industry_name":"体育"},
    {"industry_code":"881", "industry_name":"体育组织"},
    {"industry_code":"8810","industry_name":"体育组织"},
    {"industry_code":"882", "industry_name":"体育场馆"},
    {"industry_code":"8820","industry_name":"体育场馆"},
    {"industry_code":"883", "industry_name":"休闲健身活动"},
    {"industry_code":"8830","industry_name":"休闲健身活动"},
    {"industry_code":"889", "industry_name":"其他体育"},
    {"industry_code":"8890","industry_name":"其他体育"},
    {"industry_code":"89",  "industry_name":"娱乐业"},
    {"industry_code":"891", "industry_name":"室内娱乐活动"},
    {"industry_code":"8911","industry_name":"歌舞厅娱乐活动"},
    {"industry_code":"8912","industry_name":"电子游艺厅娱乐活动"},
    {"industry_code":"8913","industry_name":"网吧活动"},
    {"industry_code":"8919","industry_name":"其他室内娱乐活动"},
    {"industry_code":"892", "industry_name":"游乐园"},
    {"industry_code":"8920","industry_name":"游乐园"},
    {"industry_code":"893", "industry_name":"彩票活动"},
    {"industry_code":"8930","industry_name":"彩票活动"},
    {"industry_code":"894", "industry_name":"文化、娱乐、体育经纪代理"},
    {"industry_code":"8941","industry_name":"文化娱乐经纪人"},
    {"industry_code":"8942","industry_name":"体育经纪人"},
    {"industry_code":"8949","industry_name":"其他文化艺术经纪代理"},
    {"industry_code":"899", "industry_name":"其他娱乐业"},
    {"industry_code":"8990","industry_name":"其他娱乐业"},
    {"industry_code":"S",   "industry_name":"公共管理、社会保障和社会组织"},
    {"industry_code":"90",  "industry_name":"中国共产党机关"},
    {"industry_code":"900", "industry_name":"中国共产党机关"},
    {"industry_code":"9000","industry_name":"中国共产党机关"},
    {"industry_code":"91",  "industry_name":"国家机构"},
    {"industry_code":"911", "industry_name":"国家权力机构"},
    {"industry_code":"9110","industry_name":"国家权力机构"},
    {"industry_code":"912", "industry_name":"国家行政机构"},
    {"industry_code":"9121","industry_name":"综合事务管理机构"},
    {"industry_code":"9122","industry_name":"对外事务管理机构"},
    {"industry_code":"9123","industry_name":"公共安全管理机构"},
    {"industry_code":"9124","industry_name":"社会事务管理机构"},
    {"industry_code":"9125","industry_name":"经济事务管理机构"},
    {"industry_code":"9126","industry_name":"行政监督检查机构"},
    {"industry_code":"913", "industry_name":"人民法院和人民检察院"},
    {"industry_code":"9131","industry_name":"人民法院"},
    {"industry_code":"9132","industry_name":"人民检察院"},
    {"industry_code":"919", "industry_name":"其他国家机构"},
    {"industry_code":"9190","industry_name":"其他国家机构"},
    {"industry_code":"92",  "industry_name":"人民政协、民主党派"},
    {"industry_code":"921", "industry_name":"人民政协"},
    {"industry_code":"9210","industry_name":"人民政协"},
    {"industry_code":"922", "industry_name":"民主党派"},
    {"industry_code":"9220","industry_name":"民主党派"},
    {"industry_code":"93",  "industry_name":"社会保障"},
    {"industry_code":"930", "industry_name":"社会保障"},
    {"industry_code":"9300","industry_name":"社会保障"},
    {"industry_code":"94",  "industry_name":"群众团体、社会团体和其他成员组织"},
    {"industry_code":"941", "industry_name":"群众团体"},
    {"industry_code":"9411","industry_name":"工会"},
    {"industry_code":"9412","industry_name":"妇联"},
    {"industry_code":"9413","industry_name":"共青团"},
    {"industry_code":"9419","industry_name":"其他群众团体"},
    {"industry_code":"942", "industry_name":"社会团体"},
    {"industry_code":"9421","industry_name":"专业性团体"},
    {"industry_code":"9422","industry_name":"行业性团体"},
    {"industry_code":"9429","industry_name":"其他社会团体"},
    {"industry_code":"943", "industry_name":"基金会"},
    {"industry_code":"9430","industry_name":"基金会"},
    {"industry_code":"944", "industry_name":"宗教组织"},
    {"industry_code":"9440","industry_name":"宗教组织"},
    {"industry_code":"95",  "industry_name":"基层群众自治组织"},
    {"industry_code":"951", "industry_name":"社区自治组织"},
    {"industry_code":"9510","industry_name":"社区自治组织"},
    {"industry_code":"952", "industry_name":"村民自治组织"},
    {"industry_code":"9520","industry_name":"村民自治组织"},
    {"industry_code":"T",   "industry_name":"国际组织"},
    {"industry_code":"96",  "industry_name":"国际组织"},
    {"industry_code":"960", "industry_name":"国际组织"},
    {"industry_code":"9600","industry_name":"国际组织"}
],
    industryCodeFir={
        "A":["01","02","03","04","05"],
        "B":["06","07","08","09","10","11","12"],
        "C":["13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43"],
        "D":["44","45","46"],
        "E":["47","48","49","50"],
        "F":["51","52"],
        "G":["53","54","55","56","57","58","59","60"],
        "H":["61","62"],
        "I":["63","64","65"],
        "J":["66","67","68","69"],
        "K":["70"],
        "L":["71","72"],
        "M":["73","74","75"],
        "N":["76","77","78"],
        "O":["79","80","81"],
        "P":["82"],
        "Q":["83","84"],
        "R":["85","86","87","88","89"],
        "S":["90","91","92","93","94","95"],
        "T":["96"]
    };
